# Generated by Django 2.2.6 on 2021-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_smsrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
