# Generated by Django 2.2.6 on 2019-11-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nakhll_market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='FK_Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_Ticketing', to='nakhll_market.Product', verbose_name='محصول مدنظر'),
        ),
        migrations.AddField(
            model_name='ticketing',
            name='FK_Responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Responder_Ticketing', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده'),
        ),
        migrations.AddField(
            model_name='ticketing',
            name='FK_Shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shop_Ticketing', to='nakhll_market.Shop', verbose_name='حجره مدنظر'),
        ),
        migrations.AddField(
            model_name='ticketing',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Ticketing', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مدنظر'),
        ),
        migrations.AddField(
            model_name='message',
            name='FK_Importer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Importer_Message', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='message',
            name='FK_Replay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ticketing_Message', to='Ticketing.Ticketing', verbose_name='پاسخ'),
        ),
    ]
