# Generated by Django 2.2.6 on 2019-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0002_auto_20191106_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='SeenStatus',
        ),
        migrations.AddField(
            model_name='ticketing',
            name='SectionType',
            field=models.CharField(choices=[('0', 'پشتیبانی'), ('1', 'مالی'), ('2', 'فنی')], default='0', max_length=1, verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='SeenStatus',
            field=models.CharField(choices=[('0', 'خوانده نشده'), ('1', 'در حال بررسی'), ('2', 'بررسی شده'), ('3', 'بسته شده')], default='0', max_length=1, verbose_name='وضعیت'),
        ),
    ]
