# Generated by Django 2.2.6 on 2019-12-18 12:16

import Ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0003_auto_20191206_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Image',
            field=models.ImageField(default='', help_text='عکس مربوط به تیکت خود را اینجا بارگذاری کنید', upload_to=Ticketing.models.PathAndRename('media/Pictures/ticket'), verbose_name='عکس تیکت'),
        ),
    ]
