# Generated by Django 2.2.6 on 2019-12-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0005_auto_20191220_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketingmessage',
            name='FK_Replay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ticketing_Message', to='Ticketing.Ticketing', verbose_name='پاسخ'),
        ),
    ]
