# Generated by Django 2.2.6 on 2019-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0007_auto_20191220_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('MobileNumber', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('Type', models.CharField(choices=[('0', 'شکایت'), ('1', 'انتقادات و پیشنهادات'), ('2', 'تماس با مدیریت')], default='0', max_length=1, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'شکایت',
                'verbose_name_plural': 'شکایت ها',
                'ordering': ('id',),
            },
        ),
    ]
