# Generated by Django 2.2.6 on 2020-01-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0009_auto_20191226_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
