# Generated by Django 2.2.6 on 2020-04-07 01:32

import Ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0011_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=Ticketing.models.PathAndRename('media/Pictures/Complaint/'), verbose_name='عکس'),
        ),
    ]
