# Generated by Django 3.1.6 on 2021-08-17 05:55

import accounting_new.interfaces
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_auto_20210807_1603'),
        ('coupon', '0002_auto_20210815_1032'),
        ('logistic', '0004_auto_20210816_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(blank=True, help_text='نام ماژولی که این فاکتور رو ایجاد کرده است. به عنوان مثال: cart', max_length=50, null=True, verbose_name='مبدا')),
                ('status', models.CharField(choices=[('completing', 'در حال تکمیل'), ('paying', 'در حال پرداخت'), ('failure', 'پرداخت ناموفق'), ('success', 'پرداخت موفق')], default='completing', max_length=10, verbose_name='وضعیت فاکتور')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فاکتور')),
                ('last_payment_request', models.DateTimeField(blank=True, null=True, verbose_name='آخرین درخواست پرداخت')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='logistic.address', verbose_name='آدرس')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='cart.cart', verbose_name='سبد خرید')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='coupon.coupon', verbose_name='کوپن')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
            bases=(models.Model, accounting_new.interfaces.AccountingInterface),
        ),
    ]
