# Generated by Django 3.1.6 on 2021-09-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='coupon',
        ),
    ]
