# Generated by Django 3.1.6 on 2021-09-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210912_1617'),
        ('accounting_new', '0004_auto_20210929_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='cart.cart', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('completing', 'در حال تکمیل'), ('paying', 'در حال پرداخت'), ('preparing_product', 'در حال آماده سازی'), ('AWAITING_SHOP_APPROV', 'در انتظار تأیید فروشگاه'), ('failure', 'پرداخت ناموفق'), ('success', 'پرداخت موفق')], default='completing', max_length=20, verbose_name='وضعیت فاکتور'),
        ),
    ]
