# Generated by Django 3.1.6 on 2021-10-02 10:06

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0006_auto_20211002_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extra_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('awaiting_paying', 'در انتظار پرداخت'), ('paying', 'در حال پرداخت'), ('wait_store_approv', 'در انتظار تأیید فروشگاه'), ('preparing_product', 'در حال آماده سازی'), ('wait_customer_approv', 'در انتظار تأیید مشتری'), ('wait_store_checkout', 'در انتظار تسویه با فروشگاه'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='awaiting_paying', max_length=20, verbose_name='وضعیت فاکتور'),
        ),
    ]
