# Generated by Django 3.1.6 on 2021-10-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0008_auto_20211003_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final_coupon_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی کوپن'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_invoice_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی فاکتور'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_logistic_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی حمل و نقل'),
        ),
    ]
