# Generated by Django 3.1.6 on 2021-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0015_remove_invoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='last_payment_request',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_request_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست پرداخت'),
        ),
    ]
