# Generated by Django 3.1.6 on 2021-10-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0016_auto_20211004_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('awaiting_paying', 'در انتظار پرداخت'), ('wait_store_approv', 'در انتظار تأیید فروشگاه'), ('preparing_product', 'در حال آماده سازی'), ('wait_customer_approv', 'در انتظار تأیید مشتری'), ('wait_store_checkout', 'در انتظار تسویه با فروشگاه'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='awaiting_paying', max_length=20, verbose_name='وضعیت فاکتور'),
        ),
    ]
