# Generated by Django 3.1.6 on 2021-10-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0022_invoice_logistic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='invoice_items', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='image_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='invoice_items', verbose_name='تصویر کوچک'),
        ),
    ]
