# Generated by Django 3.1.6 on 2021-10-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0023_auto_20211008_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد بارکد'),
        ),
    ]
