# Generated by Django 3.1.6 on 2021-12-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_new', '0026_invoice_logistic_unit_details'),
        ('accounting_new', '0026_auto_20211221_1218'),
    ]

    operations = [
    ]
