from jdatetime import timedelta

# REFERRER VISIT
REFERRER_VISIT_LIMIT = 10
REFERRER_VISIT_REWARD = 1
# REFERRER SIGNUP
REFERRER_SIGNUP_LIMIT = 2
REFERRER_SIGNUP_REWARD = 1
# REFERRER PURCHASE
REFERRER_PURCHASE_LIMIT = 1
REFERRER_PURCHASE_REWARD = 1
# REFERRAL LINK DURATION
REFERRAL_LINK_DURATION = timedelta(days=7)
