# REFERRER VISIT
REFERRER_VISIT_LIMIT = 20
REFERRER_VISIT_REWARD = 1
# REFERRER SIGNUP
REFERRER_SIGNUP_LIMIT = 20
REFERRER_SIGNUP_REWARD = 1
# REFERRER PURCHASE
REFERRER_PURCHASE_LIMIT = 20
REFERRER_PURCHASE_REWARD = 1
# PURCHASE
PURCHASE_LIMIT = 20
PURCHASE_REWARD = 1
