# Generated by Django 3.2.14 on 2022-08-06 17:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrervisitevent', name='date_created',
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,),
        migrations.AddField(
            model_name='referrervisitevent', name='ip_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,),
        migrations.AddField(
            model_name='referrervisitevent', name='platform',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,),
        migrations.AddField(
            model_name='referrervisitevent', name='referrer',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,),
        migrations.AddField(
            model_name='referrervisitevent', name='status',
            field=models.IntegerField(
                choices=[(0, 'New'),
                         (1, 'Processed'),
                         (2, 'Inactive')],
                default=0),),
        migrations.AddField(
            model_name='referrervisitevent', name='user_agent',
            field=models.TextField(default=''),
            preserve_default=False,),
        migrations.DeleteModel(name='PurchaseEvent',), ]
