# Generated by Django 3.2.14 on 2022-08-07 13:40

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0002_auto_20220806_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrerpurchaseevent',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='referrerpurchaseevent',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='referrerpurchaseevent',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='referrerpurchaseevent',
            name='date_updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referrersignupevent',
            name='date_updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referrervisitevent',
            name='date_updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
