# Generated by Django 3.2.14 on 2022-08-08 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refer', '0003_auto_20220807_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrersignupevent',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referred_signup_events', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
