# Generated by Django 3.2.14 on 2022-08-20 08:25

from django.db import migrations
import pgtrigger
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0004_alter_referrersignupevent_referred'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='referrerpurchaseevent',
            trigger=pgtrigger.Protect(condition=None, declare=None, func=None, level=pgtrigger.Level(name='ROW'), name='protect_from_deletes', operation=pgtrigger.Operation(name='DELETE'), referencing=None, timing=None, when=pgtrigger.When(name='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referrerpurchaseevent',
            trigger=pgtrigger.Protect(condition=pgtrigger.Q(('old__status__in', [1, 2])), declare=None, func=None, level=pgtrigger.Level(name='ROW'), name='protect_not_new_events_from_update', operation=pgtrigger.Operation(name='UPDATE'), referencing=None, timing=None, when=pgtrigger.When(name='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referrersignupevent',
            trigger=pgtrigger.Protect(condition=None, declare=None, func=None, level=pgtrigger.Level(name='ROW'), name='protect_from_deletes', operation=pgtrigger.Operation(name='DELETE'), referencing=None, timing=None, when=pgtrigger.When(name='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referrersignupevent',
            trigger=pgtrigger.Protect(condition=pgtrigger.Q(('old__status__in', [1, 2])), declare=None, func=None, level=pgtrigger.Level(name='ROW'), name='protect_not_new_events_from_update', operation=pgtrigger.Operation(name='UPDATE'), referencing=None, timing=None, when=pgtrigger.When(name='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referrervisitevent',
            trigger=pgtrigger.Protect(condition=None, declare=None, func=None, level=pgtrigger.Level(name='ROW'), name='protect_from_deletes', operation=pgtrigger.Operation(name='DELETE'), referencing=None, timing=None, when=pgtrigger.When(name='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referrervisitevent',
            trigger=pgtrigger.Protect(condition=pgtrigger.Q(('old__status__in', [1, 2])), declare=None, func=None, level=pgtrigger.Level(name='ROW'), name='protect_not_new_events_from_update', operation=pgtrigger.Operation(name='UPDATE'), referencing=None, timing=None, when=pgtrigger.When(name='BEFORE')),
        ),
    ]
