# Generated by Django 3.2.14 on 2022-08-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0005_events_pgtrigger_20220820_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrerpurchaseevent',
            options={'verbose_name': 'تاریخچه خرید', 'verbose_name_plural': 'تاریخچه خرید ها'},
        ),
        migrations.AlterModelOptions(
            name='referrersignupevent',
            options={'verbose_name': 'تاریخچه ثبت نام', 'verbose_name_plural': 'تاریخچه ثبت نام ها'},
        ),
        migrations.AlterModelOptions(
            name='referrervisitevent',
            options={'verbose_name': 'تاریخچه بازدید', 'verbose_name_plural': 'تاریخچه بازدید ها'},
        ),
    ]
