# Generated by Django 3.1.6 on 2021-09-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (ریال)')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سفارش')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تراکنش')),
                ('payoff_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('ipg', models.CharField(choices=[('pec', 'درگاه پرداخت پارسیان'), ('zarin', 'زرین پال')], default='pec', max_length=5, verbose_name='درگاه پرداخت')),
                ('token_request_status', models.CharField(max_length=50, null=True, verbose_name='وضعیت')),
                ('token', models.CharField(max_length=200, null=True, verbose_name='توکن')),
                ('token_request_message', models.TextField(null=True, verbose_name='پیام')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TransactionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True, verbose_name='توکن')),
                ('order_id', models.CharField(max_length=200, null=True, verbose_name='شماره سفارش')),
                ('terminal_no', models.CharField(max_length=200, null=True, verbose_name='شماره پایانه')),
                ('rrn', models.CharField(max_length=200, null=True, verbose_name='RNN')),
                ('status', models.CharField(max_length=200, null=True, verbose_name='وضعیت')),
                ('hash_card_number', models.CharField(max_length=200, null=True, verbose_name='شماره کارت هش شده')),
                ('amount', models.CharField(max_length=200, null=True, verbose_name='مبلغ (ریال)')),
                ('discounted_amount', models.CharField(max_length=200, null=True, verbose_name='میزان تخفیف')),
                ('strace_no', models.CharField(max_length=200, null=True, verbose_name='شماره trace')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='payoff.transaction', verbose_name='تراکنش')),
            ],
        ),
    ]
