# Generated by Django 3.1.6 on 2021-09-14 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionresult',
            name='strace_no',
        ),
        migrations.AddField(
            model_name='transaction',
            name='referrer_app',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ماژول ارجاع دهنده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='referrer_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل ارجاع دهنده'),
        ),
        migrations.AddField(
            model_name='transactionresult',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد تراکنش'),
            preserve_default=False,
        ),
    ]
