# Generated by Django 3.1.6 on 2021-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0002_auto_20210914_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionresult',
            name='status',
            field=models.IntegerField(default=200, verbose_name='وضعیت'),
        ),
    ]
