# Generated by Django 3.1.6 on 2021-09-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0003_auto_20210914_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionresult',
            name='reversed_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نتیجه درخواست بازگشت وجه'),
        ),
        migrations.AddField(
            model_name='transactionresult',
            name='reversed_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت درخواست بازگشت وجه'),
        ),
        migrations.AddField(
            model_name='transactionresult',
            name='reversed_token',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='توکن درخواست بازگشت وجه'),
        ),
    ]
