# Generated by Django 3.1.6 on 2021-10-09 11:34

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0004_auto_20211001_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionresult',
            name='reversed_message',
        ),
        migrations.RemoveField(
            model_name='transactionresult',
            name='reversed_status',
        ),
        migrations.RemoveField(
            model_name='transactionresult',
            name='reversed_token',
        ),
        migrations.CreateModel(
            name='TransactionReverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='کد وضعیت')),
                ('token', models.BigIntegerField(verbose_name='توکن')),
                ('message', models.CharField(blank=True, max_length=127, null=True, verbose_name='پیام پارسیان')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('extra_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('transaction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payoff.transactionresult', verbose_name='نتیجه تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش برگشتی پارسیان',
                'verbose_name_plural': 'تراکنش های برگشتی پارسیان',
            },
        ),
        migrations.CreateModel(
            name='TransactionConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='کد وضعیت')),
                ('card_number_masked', models.CharField(max_length=127, verbose_name='شماره کارت خریدار')),
                ('token', models.BigIntegerField(verbose_name='توکن')),
                ('rrn', models.BigIntegerField(verbose_name='شماره یکتایی')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('extra_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('transaction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payoff.transactionresult', verbose_name='نتیجه تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش تایید شده پارسیان',
                'verbose_name_plural': 'تراکنش های تایید شده پارسیان',
            },
        ),
    ]
