# Generated by Django 3.1.6 on 2021-10-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0005_auto_20211009_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionresult',
            options={'verbose_name': 'نتیجه تراکنش', 'verbose_name_plural': 'نتایج تراکنش'},
        ),
    ]
