# Generated by Django 3.1.6 on 2021-12-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_auto_20211018_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionconfirmation',
            name='card_number_masked',
            field=models.CharField(blank=True, max_length=127, verbose_name='شماره کارت خریدار'),
        ),
    ]
