# Generated by Django 3.1.6 on 2022-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0007_auto_20211205_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره سفارش'),
        ),
    ]
