# Generated by Django 3.2.12 on 2022-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0008_auto_20220316_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionresult',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='سایر اطلاعات'),
        ),
        migrations.AddField(
            model_name='transactionresult',
            name='ref_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره مرجع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ipg',
            field=models.CharField(choices=[('pec', 'درگاه پرداخت پارسیان'), ('sep', 'درگاهپرداخت صادرات')], default='pec', max_length=5, verbose_name='درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='transactionconfirmation',
            name='rrn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره یکتایی'),
        ),
        migrations.AlterField(
            model_name='transactionconfirmation',
            name='token',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='transactionreverse',
            name='token',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='توکن'),
        ),
    ]
