# Generated by Django 3.1.6 on 2021-08-14 18:25

import coupon.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0106_auto_20210806_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد تخفیف')),
                ('valid_from', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ شروع')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('max_count', models.IntegerField(default=1, verbose_name='دفعات استفاده')),
                ('is_publish', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('price', models.IntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('min_price', models.IntegerField(blank=True, null=True, verbose_name='حداقل خرید')),
                ('max_price', models.IntegerField(blank=True, null=True, verbose_name='حداکثر خرید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='nakhll_market.product', verbose_name='محصول')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='nakhll_market.shop', verbose_name='حجره')),
                ('user', models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
            },
            bases=(models.Model, coupon.models.CouponValidation),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='کوپن تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کوپن تخفیف',
                'verbose_name_plural': 'استفاده از کوپن های تخفیف',
            },
        ),
    ]
