# Generated by Django 3.1.6 on 2021-08-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='price_applied',
            field=models.IntegerField(default=0, verbose_name='تخفیف اعمال شده'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupon', verbose_name='کوپن تخفیف'),
        ),
    ]
