# Generated by Django 3.1.6 on 2021-08-21 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_data(apps, schema_editor):
    from coupon.models import Coupon as NewCoupon
    from Payment.models import Coupon as PastCoupon
    for past_coupon in PastCoupon.objects.all():
        discount_amount = {'price':past_coupon.DiscountRate} if past_coupon.DiscountType == '2' else {'discount_percent':past_coupon.DiscountRate}
        if NewCoupon.objects.filter(code=past_coupon.SerialNumber).exists():
            i = 2
            while True:
                if NewCoupon.objects.filter(code=past_coupon.SerialNumber+'-'+str(i)).exists():
                    i += 1
                    continue
                else:
                    code = past_coupon.SerialNumber+'-'+str(i)
                    break
        else:
            code = past_coupon.SerialNumber

        coupon = NewCoupon(
            id = past_coupon.id,
            code = code,
            valid_from = past_coupon.StartDate.togregorian(),
            valid_to = past_coupon.EndDate.togregorian(),
            user_max_count = past_coupon.NumberOfUse,
            total_max_count = past_coupon.max_total_number_of_use,
            min_price = past_coupon.MinimumAmount,
            max_price = past_coupon.MaximumAmount,
            description = past_coupon.Description,
            title = past_coupon.Title,
            creator = past_coupon.FK_Creator,
            available = past_coupon.Available,
            log = past_coupon.Log,
            **discount_amount
        )
        coupon.save()
        coupon.users.set(past_coupon.FK_Users.all())
        coupon.shops.set(past_coupon.FK_Shops.all())
        coupon.products.set(past_coupon.FK_Products.all())
        coupon.categories.set(past_coupon.FK_Categories.all())


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0106_auto_20210806_1748'),
        ('coupon', '0002_auto_20210815_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='shop',
        ),
        migrations.AddField(
            model_name='coupon',
            name='available',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=True, verbose_name='وضعیت ثبت کوپن'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(related_name='coupons', to='nakhll_market.Category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_creator', to=settings.AUTH_USER_MODEL, verbose_name='سازنده کوپن'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='گزارش'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(related_name='coupons', to='nakhll_market.Product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='shops',
            field=models.ManyToManyField(related_name='coupons', to='nakhll_market.Shop', verbose_name='حجره'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_max_count',
            field=models.IntegerField(default=5, verbose_name='دفعات استفاده'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_max_count',
            field=models.IntegerField(default=1, verbose_name='دفعات استفاده کاربر'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
    ]
