# Generated by Django 3.1.6 on 2021-09-01 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0106_auto_20210806_1748'),
        ('invoice', '0002_remove_invoice_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0003_auto_20210821_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percent',
            new_name='presentage',
        ),
        migrations.RenameField(
            model_name='couponusage',
            old_name='used_date',
            new_name='used_datetime',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='shops',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='total_max_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user_max_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ ارزش بالا'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='invoice.invoice', verbose_name='سفارش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='available',
            field=models.BooleanField(choices=[('True', 'فعال'), ('False', 'غیر فعال')], default=True, verbose_name='وضعیت ثبت کوپن'),
        ),
        migrations.CreateModel(
            name='CouponConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ شروع')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('budget', models.IntegerField(default=0, verbose_name='بودجه کل کوپن')),
                ('max_usage_per_user', models.IntegerField(default=1, verbose_name='حداکثر دفعات استفاده کاربر')),
                ('max_usage', models.IntegerField(default=5, verbose_name='حداکثر دفعات استفاده')),
                ('min_purchase_amount', models.IntegerField(blank=True, null=True, verbose_name='حداقل مقدار خرید')),
                ('min_purchase_count', models.IntegerField(blank=True, null=True, verbose_name='حداقل تعداد خرید')),
                ('max_purchase_amount', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مقدار خرید')),
                ('max_purchase_count', models.IntegerField(blank=True, null=True, verbose_name='حداکثر تعداد خرید')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint', to='coupon.coupon', verbose_name='کوپن')),
                ('products', models.ManyToManyField(related_name='coupons', to='nakhll_market.Product', verbose_name='محصول')),
                ('shops', models.ManyToManyField(related_name='coupons', to='nakhll_market.Shop', verbose_name='حجره')),
                ('users', models.ManyToManyField(related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'محدودیت تخفیف',
                'verbose_name_plural': 'محدودیت\u200cهای تخفیف',
            },
        ),
    ]
