# Generated by Django 3.1.6 on 2021-10-01 13:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20210922_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponconstraint',
            name='extra_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='اطلاعات اضافه'),
        ),
    ]
