# Generated by Django 3.1.6 on 2021-10-03 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20211001_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponconstraint',
            name='valid_from',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='used_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ استفاده'),
        ),
    ]
