# Generated by Django 3.1.6 on 2021-10-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_auto_20211003_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='available',
            field=models.BooleanField(default=True, verbose_name='وضعیت ثبت کوپن'),
        ),
    ]
