# Generated by Django 3.1.6 on 2021-10-23 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0126_auto_20211023_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0009_auto_20211019_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponconstraint',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='nakhll_market.Product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='couponconstraint',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='nakhll_market.Shop', verbose_name='حجره'),
        ),
        migrations.AlterField(
            model_name='couponconstraint',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
