# Generated by Django 2.2.6 on 2019-11-06 09:59

import Payment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(default=Payment.models.BuildCampingCode(8), max_length=11, unique=True, verbose_name='سریال کمپین')),
                ('Title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('Description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('DiscountType', models.CharField(choices=[('1', 'درصدی'), ('2', 'اعتباری')], default='1', max_length=1, verbose_name='نوع تخفیف')),
                ('DiscountRate', models.PositiveIntegerField(verbose_name='میزان تخفیف')),
                ('CampaignType', models.CharField(choices=[('0', 'تولد'), ('1', 'مناسبتی'), ('2', 'انجمنی'), ('3', 'فروش اولی'), ('4', 'خرید اولی')], max_length=1, verbose_name='نوع کمپین')),
                ('DiscountStatus', models.CharField(blank=True, choices=[('0', 'مدیریتی'), ('1', 'حجره ای')], max_length=1, verbose_name='نوع نخفیف')),
                ('TextRequest', models.TextField(verbose_name='متن پیام دعوت نامه')),
                ('Image', models.ImageField(upload_to=Payment.models.PathAndRename('/media/Pictures/Campaign/Img/'), verbose_name='عکس')),
                ('Slider', models.ImageField(upload_to=Payment.models.PathAndRename('/media/Pictures/Campaign/Slide/'), verbose_name='اسلاید')),
                ('StartDate', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع کمپین')),
                ('EndDate', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان کمپین')),
                ('Available', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=True, verbose_name='وضعیت ثبت کمپین')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار کمپین')),
            ],
            options={
                'verbose_name': 'کمپین',
                'verbose_name_plural': 'کمپین ها',
                'ordering': ('StartDate',),
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان کوپن')),
                ('Description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('SerialNumber', models.CharField(default=Payment.models.BuildCoponCode(8), max_length=11, unique=True, verbose_name='سریال کوپن')),
                ('StartDate', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ساخت کوپن')),
                ('EndDate', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انقضا کوپن')),
                ('DiscountType', models.CharField(choices=[('1', 'درصدی'), ('2', 'اعتباری')], default='1', max_length=1, verbose_name='نوع تخفیف')),
                ('DiscountRate', models.PositiveIntegerField(verbose_name='میزان تخفیف')),
                ('DiscountStatus', models.CharField(blank=True, choices=[('0', 'مدیریتی'), ('1', 'حجره ای')], max_length=1, verbose_name='نوع نخفیف')),
                ('MinimumAmount', models.CharField(blank=True, max_length=15, verbose_name='حداقل مبلغ خرید')),
                ('MaximumAmount', models.CharField(blank=True, max_length=15, verbose_name='حداکثر مبلغ خرید')),
                ('NumberOfUse', models.PositiveSmallIntegerField(default=1, verbose_name='دفعات مجاز استفاده')),
                ('TextRequest', models.TextField(verbose_name='متن پیام دعوت نامه')),
                ('Image', models.ImageField(upload_to=Payment.models.PathAndRename('/media/Pictures/Coupon/Img/'), verbose_name='عکس')),
                ('Slider', models.ImageField(upload_to=Payment.models.PathAndRename('/media/Pictures/Coupon/Slide/'), verbose_name='اسلاید')),
                ('Available', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=True, verbose_name='وضعیت ثبت کوپن')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار کوپن')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('FactorNumber', models.CharField(default=Payment.models.BuildFactorCode(8), max_length=8, unique=True, verbose_name='شماره فاکتور')),
                ('Description', models.TextField(blank=True, max_length=350, verbose_name='توضیحات سبد خرید')),
                ('CountrPreCode', models.CharField(default='098', max_length=6, verbose_name='کد کشور')),
                ('MobileNumber', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('ZipCode', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('Address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('Location', models.CharField(blank=True, help_text='طول و عرض جغرافیایی', max_length=150, verbose_name='موقعیت مکانی')),
                ('FaxNumber', models.CharField(blank=True, max_length=8, verbose_name='شماره فکس')),
                ('CityPerCode', models.CharField(default='034', max_length=6, verbose_name='پیش شماره')),
                ('PhoneNumber', models.CharField(blank=True, max_length=8, verbose_name='شماره تلفن ثابت')),
                ('FactorType', models.CharField(choices=[('1', 'فاکتور چاپی'), ('2', 'فاکتور الکترونیکی')], default='1', max_length=1, verbose_name='نحوه تحویل فاکتور')),
                ('ShopInfo', models.BooleanField(choices=[(True, 'نمایش اطلاعات حجره'), (False, 'عدم نمایش اطلاعات حجره')], default=True, verbose_name='وضعیت نمایش اطلاعات حجره')),
                ('UserInfo', models.BooleanField(choices=[(True, 'نمایش اطلاعات شخصی'), (False, 'عدم نمایش اطلاعات شخصی')], default=True, verbose_name='وضعیت نمایش اطلاعات شخصی کاربر')),
                ('DiscountRate', models.PositiveIntegerField(default=0, verbose_name='میزان تخفیف')),
                ('DiscountType', models.CharField(blank=True, choices=[('0', 'مدیریتی'), ('1', 'حجره ای')], max_length=1, verbose_name='نوع نخفیف')),
                ('PostPrice', models.CharField(max_length=15, verbose_name='هزینه پست')),
                ('TotalPrice', models.CharField(max_length=15, verbose_name='هزینه کل')),
                ('PaymentStatus', models.BooleanField(choices=[(True, 'پرداخت شد'), (False, 'پرداخت نشده')], default=False, verbose_name='وضعیت پرداخت')),
                ('OrderDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('DeliveryDate', django_jalali.db.models.jDateField(blank=True, verbose_name='تاریخ تحویل')),
                ('OrderStatus', models.BooleanField(choices=[(True, 'سفارش آماده است'), (False, 'سفارش در حال آماده سازی است')], default=False, verbose_name='وضعیت سفارش')),
                ('Checkout', models.BooleanField(choices=[(True, 'تسویه شده'), (False, 'تسویه نشده')], default=False, verbose_name='وضعیت تسویه حساب فاکتور')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
                'ordering': ('ID',),
            },
        ),
        migrations.CreateModel(
            name='FactorPost',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ProductStatus', models.CharField(choices=[('0', 'لغو سفارش'), ('1', 'منتظر تایید حجره دار'), ('2', 'در حال آماده سازی'), ('3', 'ارسال شده'), ('4', 'دریافت شده')], default='1', max_length=1, verbose_name='وضعیت محصول')),
                ('ProductCount', models.PositiveIntegerField(default=1, verbose_name='تعداد محصول')),
            ],
            options={
                'verbose_name': 'محصول فاکتور',
                'verbose_name_plural': 'محصول فاکتور ها',
                'ordering': ('ID',),
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('Description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('Company', models.CharField(max_length=15, verbose_name='میزان مشارکت بازار نخل')),
                ('Entity', models.CharField(max_length=15, verbose_name='میزان مشارکت سازمان')),
                ('StartDate', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع خرید اقساطی')),
                ('EndDate', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان خرید اقساطی')),
                ('Available', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=True, verbose_name='وضعیت ثبت خرید اقساطی')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار خرید اقساطی')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False, verbose_name='وضعیت درخواست')),
            ],
            options={
                'verbose_name': 'دعوت نامه',
                'verbose_name_plural': 'دعوت نامه ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ManegerFactor',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ManegerFactorNumber', models.CharField(default=Payment.models.BuildFactorCode(8), max_length=8, unique=True, verbose_name='شماره فاکتور')),
                ('Description', models.TextField(blank=True, max_length=350, verbose_name='توضیحات فاکتور')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('Price', models.CharField(max_length=15, verbose_name='مبلغ')),
            ],
            options={
                'verbose_name': 'فاکتور مدیریت',
                'verbose_name_plural': 'فاکتور های مدیریت',
                'ordering': ('ID',),
            },
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('PaymentType', models.CharField(choices=[('0', 'پرداخت در محل'), ('1', 'پرداخت آنلاین'), ('2', 'پرداخت با کیف پول'), ('3', 'پرداخت با بن کارت')], max_length=1, verbose_name='نوع پرداخت')),
                ('PaymentPrice', models.CharField(max_length=15, verbose_name='مبلغ')),
            ],
            options={
                'verbose_name': 'نوع پرداخت',
                'verbose_name_plural': 'نوع پرداخت ها',
                'ordering': ('ID',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Inverntory', models.CharField(default='0', max_length=15, verbose_name='موجودی کیف پول')),
                ('CreditCard', models.CharField(default='0', max_length=15, verbose_name='موجودی کارت اعتباری')),
                ('CreditCardStatus', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='وضعیت کارت اعتباری')),
                ('FK_User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WalletManager', to=settings.AUTH_USER_MODEL, verbose_name='صاحب کیف پول')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
                'ordering': ('ID',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Price', models.CharField(max_length=15, verbose_name='مبلغ')),
                ('Description', models.TextField(blank=True, verbose_name='توضیحات تراکنش')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انجام تراکنش')),
                ('Type', models.CharField(choices=[('1', 'شارژ'), ('2', 'خرید'), ('3', 'فروش'), ('4', 'مدیریت'), ('5', 'تسویه حساب')], max_length=1, verbose_name='نوع عملیات')),
                ('FK_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TransactionUser', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('FK_Wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TransactionWallet', to='Payment.Wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ('Date',),
            },
        ),
        migrations.CreateModel(
            name='PostBarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionType', models.CharField(choices=[('1', 'حجره دار'), ('2', 'نود')], default='1', max_length=1, verbose_name='سطح دسترسی فرستنده')),
                ('BarCode', models.CharField(max_length=24, verbose_name='بارکد پستی')),
                ('FK_Factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_PostBarCode', to='Payment.Factor', verbose_name='شماره فاکتور')),
            ],
            options={
                'verbose_name': 'بارکد پستی',
                'verbose_name_plural': 'بارکد هایی پستی',
                'ordering': ('id',),
            },
        ),
    ]
