# Generated by Django 2.2.6 on 2019-11-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nakhll_market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbarcode',
            name='FK_Shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shop_Sender', to='nakhll_market.Shop', verbose_name='حجره'),
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Sender', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده محصولات'),
        ),
        migrations.AddField(
            model_name='paytype',
            name='FK_Factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Factor_PayType', to='Payment.Factor', verbose_name='پرداخت'),
        ),
        migrations.AddField(
            model_name='manegerfactor',
            name='FK_Receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Receiver_MF', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده'),
        ),
        migrations.AddField(
            model_name='manegerfactor',
            name='FK_Sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Sender_MF', to=settings.AUTH_USER_MODEL, verbose_name='واریز کننده'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='FK_Shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shop_Invitation', to='nakhll_market.Shop', verbose_name='حجره'),
        ),
        migrations.AddField(
            model_name='installment',
            name='FK_Product',
            field=models.ManyToManyField(blank=True, related_name='Product_Installment', to='nakhll_market.Product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='installment',
            name='FK_Receiver',
            field=models.ManyToManyField(blank=True, related_name='User_Installment', to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان اقساط'),
        ),
        migrations.AddField(
            model_name='installment',
            name='FK_Shop',
            field=models.ManyToManyField(blank=True, related_name='Shop_Installment', to='nakhll_market.Shop', verbose_name='حجره ها'),
        ),
        migrations.AddField(
            model_name='installment',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Installment_Accept', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='installment',
            name='FK_UserCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Creator', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='factorpost',
            name='FK_Facktor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Factor_Products', to='Payment.Factor', verbose_name='محصولات فاکتور'),
        ),
        migrations.AddField(
            model_name='factorpost',
            name='FK_Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_Product', to='nakhll_market.Product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='factor',
            name='FK_Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='factor',
            name='FK_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserFactor', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فاکتور'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coupon_Creator', to=settings.AUTH_USER_MODEL, verbose_name='سازنده کوپن'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_InvitationShops',
            field=models.ManyToManyField(blank=True, related_name='Coupon_Invitation_Shop', to='Payment.Invitation', verbose_name='حجره های دعوت شده'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_Products',
            field=models.ManyToManyField(blank=True, related_name='ProductCoupon', to='nakhll_market.Product', verbose_name='محصولات مجاز'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_Shops',
            field=models.ManyToManyField(blank=True, related_name='ShopCoupon', to='nakhll_market.Shop', verbose_name='حجره های مجاز'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coupon_Accept', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_Users',
            field=models.ManyToManyField(blank=True, related_name='UserCoupon', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='FK_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Campaign_Creator', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='FK_InvitationShops',
            field=models.ManyToManyField(blank=True, related_name='Campaign_Invitation_Shop', to='Payment.Invitation', verbose_name='حجره های دعوت شده'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='FK_Products',
            field=models.ManyToManyField(blank=True, related_name='ProductCampaign', to='nakhll_market.Product', verbose_name='محصولات مجاز'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='FK_Shops',
            field=models.ManyToManyField(blank=True, related_name='ShopCampaign', to='nakhll_market.Shop', verbose_name='حجره های مجاز'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Campaign_Accept', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
    ]
