# Generated by Django 2.2.6 on 2019-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20191106_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='OrderStatus',
            field=models.CharField(choices=[('0', 'سفارش تحویل داده شده است'), ('1', 'سفارش آماده است'), ('2', 'سفارش در حال آماده سازی است')], default='2', max_length=1, verbose_name='وضعیت سفارش'),
        ),
    ]
