# Generated by Django 2.2.6 on 2019-12-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_auto_20191214_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorpost',
            name='FK_Facktor',
        ),
        migrations.AddField(
            model_name='factor',
            name='FK_FactorPost',
            field=models.ManyToManyField(blank=True, related_name='Factor_Products', to='Payment.FactorPost', verbose_name='محصولات فاکتور'),
        ),
    ]
