# Generated by Django 2.2.6 on 2019-12-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_auto_20191215_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='DiscountStatus',
            field=models.CharField(blank=True, choices=[('0', 'مدیریتی'), ('1', 'حجره ای')], max_length=1, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='MobileNumber',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل'),
        ),
    ]
