# Generated by Django 2.2.6 on 2019-12-16 09:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_auto_20191216_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='DeliveryDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
