# Generated by Django 2.2.6 on 2019-12-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_auto_20191216_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorpost',
            name='FK_Factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Factor_item', to='Payment.Factor', verbose_name='فاکتور'),
        ),
    ]
