# Generated by Django 2.2.6 on 2019-12-16 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0007_factorpost_fk_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorpost',
            name='FK_Factor',
        ),
        migrations.AddField(
            model_name='factorpost',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_Product', to=settings.AUTH_USER_MODEL, verbose_name='کاربر خریدار'),
        ),
    ]
