# Generated by Django 2.2.6 on 2019-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0013_auto_20191215_0024'),
        ('Payment', '0008_auto_20191216_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorpost',
            name='FK_AttrPrice',
            field=models.ManyToManyField(blank=True, related_name='ttrPrice_Factor', to='nakhll_market.AttrPrice', verbose_name='ویژگی های انتخابی'),
        ),
    ]
