# Generated by Django 2.2.6 on 2019-12-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_factorpost_fk_attrprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorpost',
            name='FK_AttrPrice',
            field=models.ManyToManyField(blank=True, related_name='attrPrice_Factor', to='nakhll_market.AttrPrice', verbose_name='ویژگی های انتخابی'),
        ),
    ]
