# Generated by Django 2.2.6 on 2019-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_auto_20191216_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='OrderStatus',
            field=models.CharField(choices=[('0', 'سفارش تحویل داده شده است'), ('1', 'سفارش آماده است'), ('2', 'سفارش در حال آماده سازی است'), ('3', 'منتظر بررسی')], default='2', max_length=1, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='factorpost',
            name='ProductStatus',
            field=models.CharField(choices=[('0', 'لغو سفارش'), ('1', 'منتظر تایید حجره دار'), ('2', 'در حال آماده سازی'), ('3', 'ارسال شده')], default='1', max_length=1, verbose_name='وضعیت محصول'),
        ),
    ]
