# Generated by Django 2.2.6 on 2019-12-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_auto_20191220_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='City',
            field=models.CharField(blank=True, max_length=50, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='factor',
            name='State',
            field=models.CharField(blank=True, max_length=50, verbose_name='استان'),
        ),
    ]
