# Generated by Django 2.2.6 on 2020-01-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0012_auto_20191223_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار فاکتور'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FK_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_Accept', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
    ]
