# Generated by Django 2.2.6 on 2020-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0013_auto_20200102_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorpost',
            name='Description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
