# Generated by Django 2.2.6 on 2020-01-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0015_auto_20200106_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='OrderStatus',
            field=models.CharField(choices=[('0', 'سفارش تحویل داده شده است'), ('1', 'سفارش آماده است'), ('2', 'سفارش در حال آماده سازی است'), ('3', 'منتظر بررسی'), ('4', 'سفارش لغو شده است'), ('5', 'سفارش ارسال شده است')], default='2', max_length=1, verbose_name='وضعیت سفارش'),
        ),
    ]
