# Generated by Django 2.2.6 on 2020-01-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0016_auto_20200116_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbarcode',
            name='FK_Shop',
        ),
    ]
