# Generated by Django 2.2.6 on 2020-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0017_remove_postbarcode_fk_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='DiscountType',
            field=models.CharField(blank=True, choices=[('0', 'بدون کوپن'), ('1', 'مدیریتی'), ('2', 'حجره ای')], max_length=1, verbose_name='نوع نخفیف'),
        ),
    ]
