# Generated by Django 2.2.6 on 2020-01-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0019_auto_20200121_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='Slider',
        ),
    ]
