# Generated by Django 2.2.6 on 2020-01-24 15:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0020_auto_20200124_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='EndDate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ انقضا کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='StartDate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ساخت کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='TextRequest',
            field=models.TextField(blank=True, verbose_name='متن پیام دعوت نامه'),
        ),
    ]
