# Generated by Django 2.2.6 on 2020-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0021_auto_20200124_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='SerialNumber',
            field=models.CharField(max_length=11, unique=True, verbose_name='سریال کوپن'),
        ),
    ]
