# Generated by Django 2.2.6 on 2020-01-26 13:43

import Payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0022_auto_20200126_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='SerialNumber',
            field=models.CharField(default=Payment.models.BuildCoponCode(8), max_length=11, unique=True, verbose_name='سریال کوپن'),
        ),
    ]
