# Generated by Django 2.2.6 on 2020-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0024_auto_20200127_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='DiscountType',
            field=models.CharField(blank=True, choices=[('0', 'بدون کوپن'), ('1', 'مدیریتی'), ('2', 'حجره ای')], default='0', max_length=1, verbose_name='نوع نخفیف'),
        ),
    ]
