# Generated by Django 2.2.6 on 2020-01-30 11:14

import Payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0025_auto_20200128_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='SerialNumber',
            field=models.CharField(default=Payment.models.BuildCoponCode(8), max_length=30, unique=True, verbose_name='سریال کوپن'),
        ),
    ]
