# Generated by Django 2.2.6 on 2020-01-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0027_auto_20200130_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='SerialNumber',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='Slider',
        ),
        migrations.AddField(
            model_name='campaign',
            name='MaximumAmount',
            field=models.CharField(blank=True, max_length=15, verbose_name='حداکثر مبلغ خرید'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='MinimumAmount',
            field=models.CharField(blank=True, max_length=15, verbose_name='حداقل مبلغ خرید'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='DiscountRate',
            field=models.CharField(max_length=7, verbose_name='میزان تخفیف'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='TextRequest',
            field=models.TextField(blank=True, verbose_name='متن پیام دعوت نامه'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='DiscountRate',
            field=models.CharField(max_length=7, verbose_name='میزان تخفیف'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='DiscountType',
            field=models.CharField(blank=True, choices=[('0', 'بدون کوپن'), ('1', 'مدیریتی'), ('2', 'حجره ای'), ('3', 'کمپین')], default='0', max_length=1, verbose_name='نوع نخفیف'),
        ),
    ]
