# Generated by Django 2.2.6 on 2020-02-05 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0029_auto_20200205_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='FK_Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_Accept', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FK_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserFactor', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فاکتور'),
        ),
    ]
