# Generated by Django 2.2.6 on 2020-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0030_auto_20200206_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('1', 'شارژ'), ('2', 'خرید آنلاین'), ('3', 'فروش'), ('4', 'مدیریت'), ('5', 'تسویه حساب'), ('6', 'خرید با کیف پول')], max_length=1, verbose_name='نوع عملیات'),
        ),
    ]
