# Generated by Django 2.2.6 on 2020-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0032_auto_20200207_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='MaximumAmount',
            field=models.CharField(blank=True, default='0', max_length=15, verbose_name='حداکثر مبلغ خرید'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='MinimumAmount',
            field=models.CharField(blank=True, default='0', max_length=15, verbose_name='حداقل مبلغ خرید'),
        ),
    ]
