# Generated by Django 2.2.6 on 2020-02-22 13:47

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0034_auto_20200222_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='DiscountRate',
            field=models.CharField(blank=True, max_length=7, verbose_name='میزان تخفیف'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='DiscountType',
            field=models.CharField(choices=[('1', 'درصدی'), ('2', 'اعتباری'), ('2', 'ارسال رایگان')], default='1', max_length=1, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='EndDate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پایان کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='StartDate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع کمپین'),
        ),
    ]
