# Generated by Django 2.2.6 on 2020-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0035_auto_20200222_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='DiscountType',
            field=models.CharField(choices=[('1', 'درصدی'), ('2', 'اعتباری'), ('3', 'ارسال رایگان')], default='1', max_length=1, verbose_name='نوع تخفیف'),
        ),
    ]
