# Generated by Django 2.2.6 on 2020-02-23 07:13

import Payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0036_auto_20200222_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='FactorNumber',
            field=models.CharField(default=Payment.models.BuildFactorCode(10), max_length=10, unique=True, verbose_name='شماره فاکتور'),
        ),
    ]
