# Generated by Django 2.2.6 on 2020-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0037_auto_20200223_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytype',
            name='PaymentType',
            field=models.CharField(choices=[('0', 'پرداخت در محل'), ('1', 'پرداخت آنلاین'), ('2', 'پرداخت با کیف پول'), ('3', 'پرداخت با بن کارت'), ('4', 'پرداخت با آنلاین - کیف پول'), ('5', 'پرداخت با آنلاین - بن کارت'), ('6', 'پرداخت با کیف پول - بن کارت')], max_length=1, verbose_name='نوع پرداخت'),
        ),
    ]
