# Generated by Django 2.2.6 on 2020-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0038_auto_20200302_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorpost',
            name='EndPrice',
            field=models.CharField(default=0, max_length=15, verbose_name='قیمت نهایی'),
        ),
    ]
