# Generated by Django 2.2.6 on 2020-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0043_remove_comment_fk_shop'),
        ('Payment', '0039_factorpost_endprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbarcode',
            name='FK_Shops',
            field=models.ManyToManyField(blank=True, related_name='Shop_User_Sender', to='nakhll_market.Shop', verbose_name='حجره فرستنده'),
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='PostPrice',
            field=models.CharField(default='0', max_length=15, verbose_name='هزینه ارسال'),
        ),
    ]
