# Generated by Django 2.2.6 on 2020-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0040_auto_20200307_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbarcode',
            name='FK_User',
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='User_Sender',
            field=models.TextField(blank=True, verbose_name='فرستنده محصولات'),
        ),
    ]
