# Generated by Django 2.2.6 on 2020-03-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0041_auto_20200307_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbarcode',
            name='PermissionType',
        ),
    ]
