# Generated by Django 2.2.6 on 2020-03-09 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0042_remove_postbarcode_permissiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='FK_Staff_Checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_Checkout', to=settings.AUTH_USER_MODEL, verbose_name='تسویه کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('1', 'شارژ کیف پول'), ('2', 'خرید آنلاین'), ('3', 'فروش'), ('4', 'مدیریت'), ('5', 'تسویه حساب'), ('6', 'خرید با کیف پول'), ('7', 'شارژ بن کارت'), ('8', 'خرید با بن کارت')], max_length=1, verbose_name='نوع عملیات'),
        ),
    ]
