# Generated by Django 2.2.6 on 2020-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0045_remove_message_send'),
        ('Payment', '0043_auto_20200309_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='FK_Categories',
            field=models.ManyToManyField(blank=True, related_name='CategoryCampaign', to='nakhll_market.Category', verbose_name='دسته بندی های مجاز'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='FK_Categories',
            field=models.ManyToManyField(blank=True, related_name='CategoryCoupon', to='nakhll_market.Category', verbose_name='دسته بندی های مجاز'),
        ),
    ]
