# Generated by Django 2.2.6 on 2020-03-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0044_auto_20200314_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='Log',
            field=models.TextField(blank=True, verbose_name='لاگ'),
        ),
    ]
