# Generated by Django 2.2.6 on 2020-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0045_coupon_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='BigCity',
            field=models.CharField(blank=True, max_length=50, verbose_name='شهرستان'),
        ),
    ]
