# Generated by Django 2.2.6 on 2020-05-15 10:36

import Payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0060_auto_20200512_1400'),
        ('Payment', '0047_auto_20200506_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbarcode',
            name='FK_Shops',
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='CreateDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='FK_Products',
            field=models.ManyToManyField(blank=True, related_name='Product_Sender', to='nakhll_market.Product', verbose_name='محصول ارسال شده'),
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='Image',
            field=models.ImageField(null=True, upload_to=Payment.models.PathAndRename('media/Pictures/Barcode/'), verbose_name='عکس ارسال سفارش'),
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='SendDate',
            field=models.DateField(null=True, verbose_name='تاریخ ارسال مرسوله'),
        ),
        migrations.AddField(
            model_name='postbarcode',
            name='SendType',
            field=models.CharField(choices=[('0', 'درون شهری'), ('1', 'پست معمولی'), ('2', 'پس کرایه')], default='1', max_length=1, verbose_name='وضعیت ارسال'),
        ),
    ]
