# Generated by Django 2.2.6 on 2020-11-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0048_auto_20200515_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdditionalData', models.CharField(max_length=500, verbose_name='نام و نام خانوادگی خریدار')),
                ('Originator', models.CharField(max_length=50, verbose_name='شماره موبایل خریدار')),
                ('Amount', models.IntegerField(verbose_name='هزینه خرید')),
                ('Message', models.CharField(max_length=127, verbose_name='پیام پارسیان')),
                ('Status', models.IntegerField(verbose_name='کد وضعیت')),
                ('Factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Factor', verbose_name='فاکتور')),
            ],
        ),
    ]
