# Generated by Django 2.2.6 on 2020-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0049_pecorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecorder',
            name='Factor',
        ),
        migrations.AddField(
            model_name='pecorder',
            name='FactorNumber',
            field=models.CharField(default='0', max_length=10, unique=True, verbose_name='شماره فاکتور'),
        ),
    ]
