# Generated by Django 2.2.6 on 2020-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0050_auto_20201116_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecorder',
            name='Message',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='پیام پارسیان'),
        ),
        migrations.AlterField(
            model_name='pecorder',
            name='Status',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت'),
        ),
    ]
