# Generated by Django 2.2.6 on 2020-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0051_auto_20201116_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecorder',
            name='Token',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='توکن'),
        ),
    ]
