# Generated by Django 2.2.6 on 2020-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0055_pecconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecReverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(verbose_name='کد وضعیت')),
                ('Token', models.BigIntegerField(verbose_name='توکن')),
                ('Message', models.CharField(blank=True, max_length=127, null=True, verbose_name='پیام پارسیان')),
                ('OrderId', models.BigIntegerField(verbose_name='شماره تراکنش')),
            ],
        ),
    ]
