# Generated by Django 2.2.6 on 2020-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0056_pecreverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecconfirmation',
            name='HashCardNumber',
        ),
        migrations.AddField(
            model_name='pecconfirmation',
            name='CardNumberMasked',
            field=models.CharField(default='0', max_length=127, verbose_name='شماره کارت خریدار'),
            preserve_default=False,
        ),
    ]
