# Generated by Django 2.2.6 on 2020-11-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0057_auto_20201116_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pecconfirmation',
            options={'ordering': ('id',), 'verbose_name': 'تایید تراکنش پارسیان', 'verbose_name_plural': 'تایید تراکنش های پارسیان'},
        ),
        migrations.AlterModelOptions(
            name='pecorder',
            options={'ordering': ('id',), 'verbose_name': 'درخواست تراکنش', 'verbose_name_plural': 'درخواست های تراکنش'},
        ),
        migrations.AlterModelOptions(
            name='pecreverse',
            options={'ordering': ('id',), 'verbose_name': 'ارجاع تراکنش پارسیان', 'verbose_name_plural': 'ارجاع تراکنش های پارسیان'},
        ),
        migrations.AlterModelOptions(
            name='pectransaction',
            options={'ordering': ('id',), 'verbose_name': 'تراکنش پارسیان', 'verbose_name_plural': 'تراکنش های پارسیان'},
        ),
    ]
