# Generated by Django 2.2.6 on 2020-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0058_auto_20201128_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pecconfirmation',
            options={'ordering': ('id',), 'verbose_name': 'تراکنش تایید شده پارسیان', 'verbose_name_plural': 'تراکنش های تایید شده پارسیان'},
        ),
        migrations.AlterModelOptions(
            name='pecorder',
            options={'ordering': ('id',), 'verbose_name': 'درخواست تراکنش پارسیان', 'verbose_name_plural': 'درخواست تراکنش های پارسیان'},
        ),
        migrations.AlterModelOptions(
            name='pecreverse',
            options={'ordering': ('id',), 'verbose_name': 'تراکنش برگشتی پارسیان', 'verbose_name_plural': 'تراکنش های برگشتی پارسیان'},
        ),
    ]
