# Generated by Django 3.0.5 on 2021-03-07 16:24

import Payment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0059_auto_20201201_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'ordering': ('ID',), 'verbose_name': 'صورت حساب', 'verbose_name_plural': 'صورت حساب ها'},
        ),
        migrations.AlterModelOptions(
            name='factorpost',
            options={'ordering': ('ID',), 'verbose_name': 'محصول صورت حساب', 'verbose_name_plural': 'محصول صورت حساب ها'},
        ),
        migrations.AlterModelOptions(
            name='manegerfactor',
            options={'ordering': ('ID',), 'verbose_name': 'صورت حساب مدیریت', 'verbose_name_plural': 'صورت حساب های مدیریت'},
        ),
        migrations.AlterField(
            model_name='factor',
            name='Checkout',
            field=models.BooleanField(choices=[(True, 'تسویه شده'), (False, 'تسویه نشده')], default=False, verbose_name='وضعیت تسویه حساب صورت حساب'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FK_FactorPost',
            field=models.ManyToManyField(blank=True, related_name='Factor_Products', to='Payment.FactorPost', verbose_name='محصولات صورت حساب'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FK_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserFactor', to=settings.AUTH_USER_MODEL, verbose_name='صاحب صورت حساب'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FactorNumber',
            field=models.CharField(default=Payment.models.BuildFactorCode(10), max_length=10, unique=True, verbose_name='شماره صورت حساب'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FactorType',
            field=models.CharField(choices=[('1', 'صورت حساب چاپی'), ('2', 'صورت حساب الکترونیکی')], default='1', max_length=1, verbose_name='نحوه تحویل صورت حساب'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار صورت حساب'),
        ),
        migrations.AlterField(
            model_name='manegerfactor',
            name='Description',
            field=models.TextField(blank=True, max_length=350, verbose_name='توضیحات صورت حساب'),
        ),
        migrations.AlterField(
            model_name='manegerfactor',
            name='ManegerFactorNumber',
            field=models.CharField(default=Payment.models.BuildFactorCode(8), max_length=8, unique=True, verbose_name='شماره صورت حساب'),
        ),
        migrations.AlterField(
            model_name='pecorder',
            name='FactorNumber',
            field=models.CharField(default='0', max_length=10, verbose_name='شماره صورت حساب'),
        ),
        migrations.AlterField(
            model_name='postbarcode',
            name='FK_Factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_PostBarCode', to='Payment.Factor', verbose_name='شماره صورت حساب'),
        ),
    ]
