# Generated by Django 3.1.6 on 2021-03-18 06:51

import Payment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0086_historicalproduct_historicalprofile_historicalshop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0060_auto_20210307_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWallet',
            fields=[
                ('ID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('Inverntory', models.CharField(default='0', max_length=15, verbose_name='موجودی کیف پول')),
                ('CreditCard', models.CharField(default='0', max_length=15, verbose_name='موجودی کارت اعتباری')),
                ('CreditCardStatus', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='وضعیت کارت اعتباری')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('FK_User', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='صاحب کیف پول')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical کیف پول',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFactorPost',
            fields=[
                ('ID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('ProductStatus', models.CharField(choices=[('0', 'لغو سفارش'), ('1', 'منتظر تایید حجره دار'), ('2', 'در حال آماده سازی'), ('3', 'ارسال شده')], default='1', max_length=1, verbose_name='وضعیت محصول')),
                ('ProductCount', models.PositiveIntegerField(default=1, verbose_name='تعداد محصول')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('EndPrice', models.CharField(default=0, max_length=15, verbose_name='قیمت نهایی')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('FK_Product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nakhll_market.product', verbose_name='محصول')),
                ('FK_User', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر خریدار')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical محصول صورت حساب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFactor',
            fields=[
                ('ID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('FactorNumber', models.CharField(db_index=True, default=Payment.models.BuildFactorCode(10), max_length=10, verbose_name='شماره صورت حساب')),
                ('Description', models.TextField(blank=True, max_length=350, verbose_name='توضیحات سبد خرید')),
                ('CountrPreCode', models.CharField(default='098', max_length=6, verbose_name='کد کشور')),
                ('MobileNumber', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('ZipCode', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('Address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('Location', models.CharField(blank=True, help_text='طول و عرض جغرافیایی', max_length=150, verbose_name='موقعیت مکانی')),
                ('FaxNumber', models.CharField(blank=True, max_length=8, verbose_name='شماره فکس')),
                ('CityPerCode', models.CharField(default='034', max_length=6, verbose_name='پیش شماره')),
                ('City', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('BigCity', models.CharField(blank=True, max_length=50, verbose_name='شهرستان')),
                ('State', models.CharField(blank=True, max_length=50, verbose_name='استان')),
                ('PhoneNumber', models.CharField(blank=True, max_length=8, verbose_name='شماره تلفن ثابت')),
                ('FactorType', models.CharField(choices=[('1', 'صورت حساب چاپی'), ('2', 'صورت حساب الکترونیکی')], default='1', max_length=1, verbose_name='نحوه تحویل صورت حساب')),
                ('ShopInfo', models.BooleanField(choices=[(True, 'نمایش اطلاعات حجره'), (False, 'عدم نمایش اطلاعات حجره')], default=True, verbose_name='وضعیت نمایش اطلاعات حجره')),
                ('UserInfo', models.BooleanField(choices=[(True, 'نمایش اطلاعات شخصی'), (False, 'عدم نمایش اطلاعات شخصی')], default=True, verbose_name='وضعیت نمایش اطلاعات شخصی کاربر')),
                ('DiscountRate', models.PositiveIntegerField(default=0, verbose_name='میزان تخفیف')),
                ('DiscountType', models.CharField(blank=True, choices=[('0', 'بدون کوپن'), ('1', 'مدیریتی'), ('2', 'حجره ای')], default='0', max_length=1, verbose_name='نوع نخفیف')),
                ('CampaingType', models.CharField(blank=True, choices=[('0', 'بدون کمپین'), ('1', 'تولد'), ('2', 'مناسبتی'), ('3', 'انجمنی'), ('4', 'فروش اولی'), ('5', 'خرید اولی')], default='0', max_length=1, verbose_name='نوع کمپین')),
                ('PostPrice', models.CharField(max_length=15, verbose_name='هزینه پست')),
                ('TotalPrice', models.CharField(max_length=15, verbose_name='هزینه کل')),
                ('PaymentStatus', models.BooleanField(choices=[(True, 'پرداخت شد'), (False, 'پرداخت نشده')], default=False, verbose_name='وضعیت پرداخت')),
                ('PaymentType', models.CharField(choices=[('0', 'پرداخت در محل'), ('1', 'پرداخت آنلاین'), ('2', 'پرداخت با کیف پول'), ('3', 'پرداخت با بن کارت'), ('4', 'پرداخت با آنلاین - کیف پول'), ('5', 'پرداخت با آنلاین - بن کارت'), ('6', 'پرداخت با کیف پول - بن کارت')], default='1', max_length=1, verbose_name='نوع پرداخت')),
                ('OrderDate', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ خرید')),
                ('DeliveryDate', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('OrderStatus', models.CharField(choices=[('0', 'سفارش تحویل داده شده است'), ('1', 'سفارش آماده است'), ('2', 'سفارش در حال آماده سازی است'), ('3', 'منتظر بررسی'), ('4', 'سفارش لغو شده است'), ('5', 'سفارش ارسال شده است')], default='3', max_length=1, verbose_name='وضعیت سفارش')),
                ('Checkout', models.BooleanField(choices=[(True, 'تسویه شده'), (False, 'تسویه نشده')], default=False, verbose_name='وضعیت تسویه حساب صورت حساب')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار صورت حساب')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('FK_Campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Payment.campaign', verbose_name='کد کمپین')),
                ('FK_Coupon', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Payment.coupon', verbose_name='کد تخفیف')),
                ('FK_Staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('FK_Staff_Checkout', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تسویه کننده')),
                ('FK_User', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='صاحب صورت حساب')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical صورت حساب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
