# Generated by Django 3.1.6 on 2021-05-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0061_auto_20210419_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_total_number_of_use',
            field=models.IntegerField(default=10, verbose_name='تعداد کل استفاده'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='FK_Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor', to='Payment.coupon', verbose_name='کد تخفیف'),
        ),
    ]
