# Generated by Django 3.1.6 on 2021-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0062_auto_20210511_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='DiscountType',
            field=models.CharField(choices=[('0', 'مدیریتی'), ('1', 'حجره ای')], default='1', max_length=1, verbose_name='نوع تخفیف'),
        ),
    ]
