# Generated by Django 3.1.6 on 2021-07-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0064_dashboardbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardBanner',
        ),
    ]
