# Generated by Django 3.1.6 on 2021-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0066_posttrackingcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttrackingcode',
            name='barcode',
            field=models.CharField(max_length=24, unique=True, verbose_name='بارکد'),
        ),
    ]
