# Generated by Django 3.1.6 on 2021-08-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0067_auto_20210720_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttrackingcode',
            name='barcode',
            field=models.CharField(max_length=24, null=True, unique=True, verbose_name='بارکد'),
        ),
        migrations.AlterField(
            model_name='posttrackingcode',
            name='post_type',
            field=models.CharField(choices=[('irpost', 'شرکت پست جمهوری اسلامی ایران'), ('tipax', 'تیپاکس'), ('incity', 'درون شهری')], default='irpost', max_length=6, verbose_name='نوع پست'),
        ),
    ]
