# Generated by Django 3.2.14 on 2022-07-17 09:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('blocked_balance__gte', django.db.models.expressions.F('blocked_cashable_amount'))), name='blocked_balance_is_more_than_or_equal_to_blocked_cashable_amount'),
        ),
    ]
