# Generated by Django 3.2.14 on 2022-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_account_blocked_balance_is_more_than_or_equal_to_blocked_cashable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار'), (1, 'تایید شده'), (2, 'رد شده')], default=0),
        ),
    ]
