# Generated by Django 3.2.14 on 2022-07-30 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20220730_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinburn',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='coinmintage',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار'),
        ),
    ]
