# Generated by Django 3.2.14 on 2022-07-30 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_auto_20220730_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMintBurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار')),
                ('is_mint', models.BooleanField(verbose_name='آیا ضرب سکه است؟')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date_created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='سوزاننده سکه')),
            ],
            options={
                'verbose_name': 'Burn',
                'verbose_name_plural': 'Burns',
            },
        ),
        migrations.RemoveField(
            model_name='coinmintage',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoinBurn',
        ),
        migrations.DeleteModel(
            name='CoinMintage',
        ),
    ]
