# Generated by Django 3.2.14 on 2022-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20220730_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinmintburn',
            options={'verbose_name': 'MintBurn', 'verbose_name_plural': 'MintBurns'},
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'درخواست تسویه'), (1, 'واریز')]),
        ),
    ]
