# Generated by Django 3.2.14 on 2022-07-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_accountrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='cashable',
            field=models.BooleanField(default=False),
        ),
    ]
