# Generated by Django 3.2.14 on 2022-08-05 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0015_auto_20220804_check_all_transactions_value_summation_must_be_zero_post_insert'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accountrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', [1, 2]), models.Q(('staff_user', None), _negated=True)), models.Q(('staff_user', None), ('status', 0)), _connector='OR'), name='staff_user_check_for_different_statuses'),
        ),
    ]
