# Generated by Django 3.2.14 on 2022-08-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20220805_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'permissions': [('confirm_accountrequest', 'Can confirm account request!'), ('reject_accountrequest', 'Can reject account request!'), ('create_accountrequest', 'Can create account request.')], 'verbose_name': 'AccountRequest', 'verbose_name_plural': 'AccountRequest'},
        ),
    ]
