# Generated by Django 3.2.14 on 2022-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_alter_accountrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='cashable_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'Referrer Visit Reward'), (2, 'Referrer Signup Reward'), (3, 'Referrer Buy Reward'), (4, 'Referred Buy Reward'), (5, 'Buy From Shop'), (6, 'Withdraw'), (7, 'Deposit')]),
        ),
    ]
