# Generated by Django 3.2.14 on 2022-08-10 05:50

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_auto_20220726_1432'),
        ('bank', '0019_alter_accountrequest_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Rial amount paid')),
                ('date_created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('account_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.accountrequest', unique=True, verbose_name='account request')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'CoinPayment',
                'verbose_name_plural': 'CoinPayments',
            },
        ),
    ]
