# Generated by Django 3.2.14 on 2022-08-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0023_alter_accountrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='cashable_value',
            field=models.IntegerField(blank=True, verbose_name='مقدار قابل تسویه از حساب مبدا'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='date_confirmed',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='date_rejected',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ رد'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account_request', to='bank.account', verbose_name='حساب مبدا'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'Referrer Visit Reward'), (1, 'Referrer Signup Reward'), (2, 'Referrer Purchase Reward'), (3, 'Purchase Reward'), (4, 'Buy From Nakhll'), (5, 'Withdraw'), (6, 'Deposit'), (7, 'Fund To Bank')], verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کارمند تایید/رد کننده'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار'), (1, 'تایید شده'), (2, 'رد شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account_request', to='bank.account', verbose_name='حساب مقصد'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='value',
            field=models.PositiveIntegerField(verbose_name='مقدار سکه'),
        ),
    ]
