# Generated by Django 3.2.14 on 2022-08-16 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_auto_20220815_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار سکه'),
        ),
        migrations.AddConstraint(
            model_name='accountrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_account', django.db.models.expressions.F('to_account')), _negated=True), name='from_account_must_not_be_equal_to_to_account'),
        ),
    ]
