# Generated by Django 3.2.14 on 2022-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_buyfromnakhllrequest_withdrawrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialToFundRequest', fields=[],
            options={'proxy': True, 'indexes': [],
                     'constraints': [], },
            bases=('bank.accountrequest',),),
        migrations.AlterField(
            model_name='accountrequest', name='request_type',
            field=models.IntegerField(
                choices=[(0, 'Referrer Visit Reward'),
                         (1, 'Referrer Signup Reward'),
                         (2, 'Referrer Purchase Reward'),
                         (3, 'Purchase Reward'),
                         (4, 'Buy From Nakhll'),
                         (5, 'Withdraw'),
                         (6, 'Deposit'),
                         (7, 'Financial To Fund')],
                verbose_name='نوع درخواست'),), ]
