# Generated by Django 3.2.14 on 2022-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_financial_to_fund_proxy_20220820_1131'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('from_account', -1), ('request_type__in', [6, 0, 1, 2, 3]), ('to_account__gt', 0)), models.Q(('from_account__gt', 0), ('request_type__in', [5, 4]), ('to_account', -2)), models.Q(('from_account', -2), ('request_type', 7), ('to_account', -1)), _connector='OR')), name='check_request_types_requirements'),
        ),
    ]
