# Generated by Django 3.2.14 on 2022-08-24 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0030_account_request_triggers_20220820_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'حساب سکه', 'verbose_name_plural': 'حساب های سکه'},
        ),
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'permissions': [('confirm_accountrequest', 'Can confirm account request!'), ('reject_accountrequest', 'Can reject account request!'), ('create_accountrequest', 'Can create account request.')], 'verbose_name': 'درخواست', 'verbose_name_plural': 'درخواست ها'},
        ),
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'verbose_name': 'سند تراکنش', 'verbose_name_plural': 'سند تراکنش ها'},
        ),
        migrations.AlterModelOptions(
            name='coinmintburn',
            options={'verbose_name': 'ضرب سکه', 'verbose_name_plural': 'ضرب سکه ها'},
        ),
        migrations.AlterModelOptions(
            name='coinpayment',
            options={'verbose_name': 'پرداخت سکه', 'verbose_name_plural': 'پرداخت سکه ها'},
        ),
        migrations.AlterModelOptions(
            name='depositrequest',
            options={'verbose_name': 'درخواست واریز', 'verbose_name_plural': 'درخواست های واریز'},
        ),
        migrations.AlterModelOptions(
            name='financialtofundrequest',
            options={'verbose_name': 'درخواست از حساب مالی به صندوق', 'verbose_name_plural': 'درخواست ها از حساب مالی به صندوق'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی مسدود شده'),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked_cashable_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='موحودی نقدی مسدود شده'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cashable_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی نقدی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='مالک حساب'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'پاداش بازدید'), (1, 'پاداش ثبت نام'), (2, 'پاداش خرید بازار یاب'), (3, 'پاداش خرید خریدار'), (4, 'خرید از نخل'), (5, 'تسویه حساب'), (6, 'واریز'), (7, 'از حساب مالی به صندوق')], verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='coinmintburn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ضرب کننده سکه'),
        ),
    ]
