# Generated by Django 3.2.14 on 2022-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_set_verbos_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountrequest',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 1)), name='request_value_must_be_greater_or_equal_to_1'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.CheckConstraint(check=models.Q(('value', 0), _negated=True), name='transaction_value_must_be_not_0'),
        ),
    ]
