# Generated by Django 3.1.6 on 2021-11-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='user_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
