# Generated by Django 3.1.6 on 2021-11-22 09:06

from django.db import migrations, models
import nakhll_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_auth', '0002_auto_20211122_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='auth_code',
            field=models.CharField(default=nakhll_auth.models.generate_uuid_code, max_length=32),
        ),
    ]
