# Generated by Django 3.1.6 on 2021-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_auth', '0004_auto_20211122_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authrequest',
            old_name='auth_code',
            new_name='auth_key',
        ),
        migrations.RenameField(
            model_name='authrequest',
            old_name='user_code',
            new_name='sms_code',
        ),
        migrations.AddField(
            model_name='authrequest',
            name='auth_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'پایان یافته')], default='pending', max_length=10),
        ),
    ]
