# Generated by Django 3.2.12 on 2022-07-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_auth', '0005_auto_20211124_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrequest',
            name='referral_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
