# Generated by Django 2.2.6 on 2020-03-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200130_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='Point',
            field=models.FloatField(default=0.0, verbose_name='امتیاز'),
        ),
    ]
