# Generated by Django 2.2.6 on 2020-03-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200302_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(verbose_name='توضیخات نظر')),
                ('Available', models.BooleanField(default=False, verbose_name='وضعیت انتشار نظر')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')),
                ('FK_Like', models.ManyToManyField(blank=True, related_name='Post_Comment_Like', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده')),
                ('FK_Pater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.CommentPost', verbose_name='ریپلای شده')),
                ('FK_Post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.PostBlog', verbose_name='پست')),
                ('FK_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VisiteComment', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('FK_UserAdder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AddComment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر پست',
                'verbose_name_plural': 'نظرات پست',
                'ordering': ('id',),
            },
        ),
    ]
