# Generated by Django 2.2.6 on 2020-03-04 13:06

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_postblog_fk_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorstory',
            name='Image',
        ),
        migrations.AddField(
            model_name='vendorstory',
            name='FK_Point',
            field=models.ManyToManyField(blank=True, related_name='Story_Point', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز دهنده'),
        ),
        migrations.AddField(
            model_name='vendorstory',
            name='Shop_Image',
            field=models.ImageField(blank=True, help_text='در صورتی که نمی خواهید از عکس حجره دار استفاده شود، عکس جایگزین را اینجا وارد نمایید.', null=True, upload_to=blog.models.PathAndRename('media/Pictures/Markets/SubMarkets/Shops/VendorStory/'), verbose_name='عکس حجره دار'),
        ),
        migrations.AddField(
            model_name='vendorstory',
            name='Show_Image',
            field=models.BooleanField(choices=[(True, 'نمایش عکس جایگزین'), (False, 'نمایش عکس پروفایل حجره دار')], default=False, help_text='وضعیت عکس حجره دار را اینجا مشخص نمایید.', verbose_name='نمایش عکس جایگزین'),
        ),
        migrations.AddField(
            model_name='vendorstory',
            name='Slider',
            field=models.ImageField(blank=True, help_text='عکسی که در بالای صفحه داستان محصول قرار می گیرد را اینجا وارد نمایید.', null=True, upload_to=blog.models.PathAndRename('media/Pictures/Markets/SubMarkets/Shops/VendorStory/'), verbose_name='اسلایدر'),
        ),
        migrations.AlterField(
            model_name='vendorstory',
            name='Point',
            field=models.FloatField(default=0.0, verbose_name='امتیاز'),
        ),
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(verbose_name='توضیخات نظر')),
                ('Available', models.BooleanField(default=False, verbose_name='وضعیت انتشار نظر')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')),
                ('FK_Like', models.ManyToManyField(blank=True, related_name='Story_Comment_Like', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده')),
                ('FK_Pater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.StoryPost', verbose_name='ریپلای شده')),
                ('FK_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserVisiteComment', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('FK_UserAdder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserAdder', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('FK_VendorStory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.VendorStory', verbose_name='داستان')),
            ],
            options={
                'verbose_name': 'نظر داستان',
                'verbose_name_plural': 'نظرات داستان',
                'ordering': ('id',),
            },
        ),
    ]
