# Generated by Django 2.2.6 on 2020-03-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0041_auto_20200303_1816'),
        ('blog', '0006_auto_20200304_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstory',
            name='FK_Tag',
            field=models.ManyToManyField(blank=True, related_name='Story_Tag', to='nakhll_market.Tag', verbose_name='تگ ها'),
        ),
    ]
