# Generated by Django 2.2.6 on 2020-03-09 00:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_vendorstory_fk_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='Image',
        ),
        migrations.AddField(
            model_name='postblog',
            name='Index_Image',
            field=models.ImageField(default='static/images/banner_default.jpg', help_text='تصویری که در صفحه اصلی نمایش داده می شود را اینجا بارگذاری نمایید.', upload_to=blog.models.PathAndRename('media/Pictures/Blog/Post/IndexImage/'), verbose_name='تصویر صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='postblog',
            name='Slider',
            field=models.ImageField(blank=True, help_text='تصویری که به صورت اسلایدر در صفحه پست نمایش داده می شود را اینجا بارگذاری نمایید.', null=True, upload_to=blog.models.PathAndRename('media/Pictures/Blog/Post/Slider/'), verbose_name='اسلایدر پست'),
        ),
    ]
