# Generated by Django 3.1.5 on 2021-02-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200309_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='FK_Like',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='FK_Pater',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='FK_Post',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='FK_User',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='FK_UserAdder',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='FK_Category',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='FK_Point',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='FK_Shop',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='FK_Tag',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='FK_User',
        ),
        migrations.RemoveField(
            model_name='storypost',
            name='FK_Like',
        ),
        migrations.RemoveField(
            model_name='storypost',
            name='FK_Pater',
        ),
        migrations.RemoveField(
            model_name='storypost',
            name='FK_User',
        ),
        migrations.RemoveField(
            model_name='storypost',
            name='FK_UserAdder',
        ),
        migrations.RemoveField(
            model_name='storypost',
            name='FK_VendorStory',
        ),
        migrations.RemoveField(
            model_name='vendorstory',
            name='FK_Point',
        ),
        migrations.RemoveField(
            model_name='vendorstory',
            name='FK_Shop',
        ),
        migrations.RemoveField(
            model_name='vendorstory',
            name='FK_Tag',
        ),
        migrations.RemoveField(
            model_name='vendorstory',
            name='FK_User',
        ),
        migrations.DeleteModel(
            name='CategoryBlog',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='PostBlog',
        ),
        migrations.DeleteModel(
            name='StoryPost',
        ),
        migrations.DeleteModel(
            name='VendorStory',
        ),
    ]
