# Generated by Django 2.2.6 on 2019-11-06 11:58

from django.db import migrations, models
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submarket',
            name='Image',
            field=models.ImageField(help_text='عکس مورد نظر را اینجا وارد کنید', null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/Markets/SubMarkets/'), verbose_name='عکس راسته'),
        ),
    ]
