# Generated by Django 2.2.6 on 2019-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0003_auto_20191106_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Location',
            field=models.CharField(choices=[('1', 'صفحه اصلی'), ('2', 'تبلیغات صفحه اصلی - پایین'), ('3', 'تبلیغات صفحه اصلی - وسط'), ('4', 'بنر صفحه بازارچه ها')], default='1', max_length=2, verbose_name='مکان اسلایدر'),
        ),
    ]
