# Generated by Django 2.2.6 on 2019-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0004_auto_20191110_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='ShowInfo',
            field=models.BooleanField(default=True, help_text='اگر می خواهید عنوان و توضیحات بنر روی آن نمایش داده شود، این گزینه را فعال کنید.', verbose_name='وضعیت نمایش اطلاعات اسلایدر'),
        ),
    ]
