# Generated by Django 2.2.6 on 2019-11-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0005_slider_showinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbanner',
            options={'ordering': ('id', 'Title'), 'verbose_name': 'گالری محصول', 'verbose_name_plural': 'گالری محصولات '},
        ),
        migrations.AddField(
            model_name='profile',
            name='Sex',
            field=models.CharField(choices=[('0', 'تمایلی به وارد کردن ندارم'), ('1', 'زن'), ('2', 'مرد'), ('3', 'سایر')], default='0', max_length=1, verbose_name='جنسیت'),
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('Slug', models.SlugField(unique=True, verbose_name='شناسه صفحه')),
                ('Content', tinymce.models.HTMLField(verbose_name='محتوا صفحه')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار صفحه')),
                ('DtatUpdate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی صفحه')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'پیش نویس')], default=True, verbose_name='وضعیت انتشار فیلم حجره')),
                ('FK_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Published_Page', to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده')),
            ],
            options={
                'verbose_name': 'برگه',
                'verbose_name_plural': 'برکه ها',
                'ordering': ('id',),
            },
        ),
    ]
