# Generated by Django 2.2.6 on 2019-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0007_auto_20191129_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Negative',
            field=models.TextField(blank=True, verbose_name='نقاط ضعف'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Positive',
            field=models.TextField(blank=True, verbose_name='نقاط قوت'),
        ),
    ]
