# Generated by Django 2.2.6 on 2019-12-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0009_auto_20191212_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
    ]
