# Generated by Django 2.2.6 on 2019-12-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0010_auto_20191212_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('Value', models.TextField(blank=True, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'فیلد',
                'verbose_name_plural': 'فیلد ها',
                'ordering': ('id',),
            },
        ),
        migrations.RenameField(
            model_name='newsletters',
            old_name='PhoneNumber',
            new_name='MobileNumber',
        ),
        migrations.RemoveField(
            model_name='attrprice',
            name='FK_AttrProduct',
        ),
        migrations.AddField(
            model_name='attrprice',
            name='FK_Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AttrPrice_Product', to='nakhll_market.Product', verbose_name='محصول'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part', models.CharField(choices=[('0', 'پروفایل'), ('1', 'حجره'), ('2', 'محصول'), ('3', 'ویژگی')], default='0', max_length=1, verbose_name='بخش')),
                ('Seen', models.BooleanField(choices=[(True, 'دیده شده'), (False, 'دیده نشده')], default=False, verbose_name='وضعیت بازدید')),
                ('Status', models.BooleanField(blank=True, choices=[(True, 'ثبت تغییرات'), (False, 'عدم ثبت تغییرات')], verbose_name='وضعیت تغییرات')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت هشدار')),
                ('DateUpdate', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت تغییرات')),
                ('Description', models.CharField(blank=True, help_text='در صورت عدم پذیرش تغییرات انجام شده، لطفا دلایل خودت را اینجا وارد نمایید.', max_length=250, verbose_name='توضیحات')),
                ('FK_Field', models.ManyToManyField(blank=True, related_name='Alert_Fields', to='nakhll_market.Field', verbose_name='فیلد ها')),
                ('FK_Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Alert_User_Product', to='nakhll_market.Product', verbose_name='محصول')),
                ('FK_Shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Alert_User_Shop', to='nakhll_market.Shop', verbose_name='حجره')),
                ('FK_Staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Alert_User_Published', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('FK_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Registrar_Alert', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدار ها',
                'ordering': ('id',),
            },
        ),
    ]
