# Generated by Django 2.2.6 on 2019-12-14 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0012_auto_20191214_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='FK_UserAdder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='review',
            name='FK_UserAdder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Review', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
