# Generated by Django 2.2.6 on 2019-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0013_auto_20191215_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('Code', models.CharField(max_length=6, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'کد اهراز هویت',
                'verbose_name_plural': 'کد های اهراز هویت',
                'ordering': ('id',),
            },
        ),
    ]
