# Generated by Django 2.2.6 on 2019-12-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0014_registercode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterCode',
        ),
    ]
