# Generated by Django 2.2.6 on 2019-12-17 11:57

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0015_delete_registercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BrithDay',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='TutorialWebsite',
            field=models.CharField(blank=True, choices=[('0', 'موتور های جستجو'), ('1', 'حجره داران'), ('2', 'شبکه های اجتماعی'), ('3', 'کاربران'), ('4', 'رسانه ها'), ('5', 'تبلیغات'), ('6', 'NOD'), ('7', 'سایر'), ('8', 'هیچ کدام')], default=8, max_length=1, verbose_name='نحوه آشنایی با سایت'),
        ),
    ]
