# Generated by Django 2.2.6 on 2019-12-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0016_auto_20191217_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='FK_Product',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='FK_Shop',
        ),
        migrations.AddField(
            model_name='alert',
            name='Slug',
            field=models.TextField(blank=True, null=True, verbose_name='شناسه بخش'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='Part',
            field=models.CharField(choices=[('0', 'ایجاد پروفایل'), ('1', 'ویرایش پروفایل'), ('2', 'ایجاد حجره'), ('3', 'ویراش حجره'), ('4', 'ایجاد بنر حجره'), ('5', 'ویرایش بنر حجره'), ('6', 'ایجاد محصول'), ('7', 'ویراش محصول'), ('8', 'ایجاد بنر محصول'), ('9', 'ویراش بنر محصول'), ('10', 'ایجاد ویژگی جدید'), ('11', 'ثبت ویژگی جدید برای محصول'), ('12', 'ثبت سفارش'), ('13', 'لغو سفارش'), ('14', 'ثبت کامنت جدید'), ('15', 'ثبت نقد و بررسی جدید'), ('16', 'ثبت تیکت جدید')], default='0', max_length=2, verbose_name='بخش'),
        ),
    ]
