# Generated by Django 2.2.6 on 2019-12-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0018_shop_newimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='NewImage',
        ),
    ]
