# Generated by Django 2.2.6 on 2019-12-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0019_remove_shop_newimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ValidCode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='کد فعال سازی'),
        ),
    ]
