# Generated by Django 2.2.6 on 2019-12-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0020_profile_validcode'),
        ('nakhll_market', '0020_auto_20191223_0104'),
    ]

    operations = [
    ]
