# Generated by Django 2.2.6 on 2019-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0021_merge_20191223_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ValidCode',
            field=models.CharField(blank=True, default='80', max_length=8, verbose_name='کد فعال سازی'),
        ),
    ]
