# Generated by Django 2.2.6 on 2019-12-23 20:09

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0022_auto_20191223_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserphoneValid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('ValidCode', models.CharField(blank=True, default='80', max_length=8, verbose_name='کد فعال سازی')),
                ('Validation', models.BooleanField(default=False, verbose_name='تایید شماره تماس')),
                ('Date', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'فعالسازی شماره',
                'verbose_name_plural': 'فعالسازی شماره',
                'ordering': ('Date',),
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ValidCode',
        ),
    ]
