# Generated by Django 2.2.6 on 2019-12-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0024_auto_20191224_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان حجره'),
        ),
    ]
