# Generated by Django 2.2.6 on 2019-12-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0025_auto_20191224_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sex',
            field=models.CharField(choices=[('0', 'انتخاب جنسیت'), ('1', 'زن'), ('2', 'مرد'), ('3', 'سایر')], default='0', max_length=1, verbose_name='جنسیت'),
        ),
    ]
