# Generated by Django 2.2.6 on 2020-01-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0026_auto_20191225_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrprice',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=True, verbose_name='وضعیت انتشار بنر محصول'),
        ),
    ]
