# Generated by Django 2.2.6 on 2020-01-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0028_auto_20200116_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PostPrice',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پست سفارشی سازی شده'),
        ),
    ]
