# Generated by Django 2.2.6 on 2020-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0029_auto_20200118_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PostPrice',
            field=models.CharField(default='0', max_length=15, verbose_name='مبلغ پست سفارشی سازی شده'),
        ),
    ]
