# Generated by Django 2.2.6 on 2020-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0031_auto_20200122_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش بنر حجره'),
        ),
        migrations.AddField(
            model_name='productbanner',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش بنر حجره'),
        ),
        migrations.AddField(
            model_name='productmovie',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش بنر حجره'),
        ),
        migrations.AddField(
            model_name='shop',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش بنر حجره'),
        ),
        migrations.AddField(
            model_name='shopbanner',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش بنر حجره'),
        ),
        migrations.AddField(
            model_name='shopmovie',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش بنر حجره'),
        ),
    ]
