# Generated by Django 2.2.6 on 2020-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0032_auto_20200122_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.TextField(verbose_name='نکته')),
            ],
            options={
                'verbose_name': 'نکته',
                'verbose_name_plural': 'نکات',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='Negative',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Positive',
        ),
        migrations.AddField(
            model_name='review',
            name='FK_NegativeNote',
            field=models.ManyToManyField(blank=True, related_name='Review_Negative_Note', to='nakhll_market.Note', verbose_name='نقاط ضعف'),
        ),
        migrations.AddField(
            model_name='review',
            name='FK_PositiveNote',
            field=models.ManyToManyField(blank=True, related_name='Review_Positive_Note', to='nakhll_market.Note', verbose_name='نقاط قوت'),
        ),
    ]
