# Generated by Django 2.2.6 on 2020-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0033_auto_20200208_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrprice',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=True, verbose_name='وضعیت انتشار ارزش ویژگی محصول'),
        ),
        migrations.AlterField(
            model_name='attrproduct',
            name='Available',
            field=models.BooleanField(choices=[(True, 'نمایش ویژگی'), (False, 'عدم نمایش ویژگی')], default=False, verbose_name='وضعیت نمایش ویژگی محصول'),
        ),
    ]
