# Generated by Django 2.2.6 on 2020-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0034_auto_20200216_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object_Slug', models.SlugField(verbose_name='شناسه')),
                ('Object_Type', models.CharField(choices=[('0', 'حجره'), ('1', 'محصول'), ('2', 'پست وبلاگ')], default='0', max_length=1, verbose_name='نوع شیء')),
                ('View_Count', models.PositiveIntegerField(default=1, verbose_name='میزان بازدید')),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدید صفحات',
                'ordering': ('id',),
            },
        ),
    ]
