# Generated by Django 2.2.6 on 2020-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0035_pageviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Ip', models.CharField(blank=True, max_length=15, verbose_name='آدرس ای پی')),
                ('DateTime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')),
            ],
            options={
                'verbose_name': 'بازدید کننده',
                'verbose_name_plural': 'بازدید کنندگان',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='pageviews',
            name='FK_Viewer',
            field=models.ManyToManyField(blank=True, related_name='View_Users', to='nakhll_market.User_View', verbose_name='بازدید کنندگان'),
        ),
    ]
