# Generated by Django 2.2.6 on 2020-02-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0036_auto_20200223_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviews',
            name='Object_Type',
            field=models.CharField(choices=[('0', 'حجره'), ('1', 'محصول'), ('2', 'پست وبلاگ'), ('3', 'داستان حجره')], default='0', max_length=1, verbose_name='نوع شیء'),
        ),
    ]
