# Generated by Django 2.2.6 on 2020-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0037_auto_20200225_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Holidays',
            field=models.CharField(blank=True, max_length=15, verbose_name='روز های تعطیلی حجره'),
        ),
    ]
