# Generated by Django 2.2.6 on 2020-03-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0038_auto_20200301_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='FK_Message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='FK_Replay',
        ),
        migrations.RemoveField(
            model_name='message',
            name='FK_User',
        ),
        migrations.RemoveField(
            model_name='pvchat',
            name='FK_Shop',
        ),
        migrations.RemoveField(
            model_name='pvchat',
            name='FK_User',
        ),
        migrations.DeleteModel(
            name='ManagerMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PVChat',
        ),
    ]
