# Generated by Django 2.2.6 on 2020-03-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0039_auto_20200303_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Message_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeenStatus', models.BooleanField(choices=[(True, 'دیده شده'), (False, 'دیده نشده')], default=False, verbose_name='وضعیت بازدید')),
                ('FK_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت پیام کاربر',
                'verbose_name_plural': 'وضعیت پیام کاربران',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=250, verbose_name='عنوان')),
                ('Text', models.TextField(verbose_name='متن')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('FK_Sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Message_Sender', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
                ('FK_Users', models.ManyToManyField(blank=True, related_name='Message_User', to='nakhll_market.User_Message_Status', verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان ها',
                'ordering': ('id',),
            },
        ),
    ]
