# Generated by Django 2.2.6 on 2020-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0040_message_user_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='FK_Users',
            field=models.ManyToManyField(related_name='Message_User', to='nakhll_market.User_Message_Status', verbose_name='کاربران'),
        ),
    ]
