# Generated by Django 2.2.6 on 2020-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0041_auto_20200303_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Type',
            field=models.BooleanField(choices=[(True, 'در حال نمایش'), (False, 'عدم نمایش')], default=True, verbose_name='وضعیت نمایش'),
        ),
    ]
