# Generated by Django 2.2.6 on 2020-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0043_remove_comment_fk_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Send',
            field=models.BooleanField(choices=[(True, 'در حال نمایش'), (False, 'عدم نمایش')], default=True, verbose_name='وضعیت ارسال'),
        ),
    ]
