# Generated by Django 2.2.6 on 2020-03-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0044_message_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Send',
        ),
    ]
