# Generated by Django 2.2.6 on 2020-03-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0045_remove_message_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Description',
            field=models.TextField(blank=True, help_text='در صورت عدم پذیرش تغییرات انجام شده، لطفا دلایل خودت را اینجا وارد نمایید.', verbose_name='توضیحات'),
        ),
    ]
