# Generated by Django 2.2.6 on 2020-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0046_auto_20200314_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=models.CharField(default='500', max_length=8, verbose_name='وزن محصول برای پست (گرم)'),
        ),
    ]
