# Generated by Django 2.2.6 on 2020-04-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0047_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='تاریخ بازدید')),
                ('Count', models.CharField(default='1', max_length=15, verbose_name='میزان بازدید')),
            ],
            options={
                'verbose_name': 'بازدید - تاریخ',
                'verbose_name_plural': 'بازدید - تاریخ ها',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='user_view',
            name='Total_View',
            field=models.CharField(default='1', max_length=15, verbose_name='میزان بازدید'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='Part',
            field=models.CharField(choices=[('0', 'ایجاد پروفایل'), ('1', 'ویرایش پروفایل'), ('2', 'ایجاد حجره'), ('3', 'ویرایش حجره'), ('4', 'ایجاد بنر حجره'), ('5', 'ویرایش بنر حجره'), ('6', 'ایجاد محصول'), ('7', 'ویرایش محصول'), ('8', 'ایجاد بنر محصول'), ('9', 'ویرایش بنر محصول'), ('10', 'ایجاد ویژگی جدید'), ('11', 'ثبت ویژگی جدید برای محصول'), ('12', 'ثبت سفارش'), ('13', 'لغو سفارش'), ('14', 'ثبت کامنت جدید'), ('15', 'ثبت نقد و بررسی جدید'), ('16', 'ثبت تیکت جدید'), ('17', 'ایجاد ارزش ویژگی جدید'), ('18', 'ثبت انتقاد و پیشنهاد یا شکایت'), ('19', 'لغو فاکتور'), ('20', 'تایید سفارش'), ('21', 'ارسال سفارش'), ('22', 'حذف بنر حجره'), ('23', 'حذف بنر محصول'), ('24', 'حذف ویژگی محصول'), ('25', 'حذف ارزش ویژگی')], default='0', max_length=2, verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش محصول'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='TutorialWebsite',
            field=models.CharField(blank=True, choices=[('0', 'موتور های جستجو'), ('1', 'حجره داران'), ('2', 'شبکه های اجتماعی'), ('3', 'کاربران'), ('4', 'رسانه ها'), ('5', 'تبلیغات'), ('6', 'NOD'), ('7', 'سایر'), ('8', 'هیچ کدام')], default='8', max_length=1, verbose_name='نحوه آشنایی با سایت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Edite',
            field=models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش حجره'),
        ),
        migrations.CreateModel(
            name='ShopViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_View', models.CharField(default='1', max_length=15, verbose_name='میزان کل بازدید')),
                ('FK_Date', models.ManyToManyField(blank=True, related_name='Shop_Date_Views', to='nakhll_market.Date_View', verbose_name='بازدید بر اساس تاریخ')),
                ('FK_Shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shop_Views', to='nakhll_market.Shop', verbose_name='حجره')),
                ('FK_Viewer', models.ManyToManyField(blank=True, related_name='Shop_View_Users', to='nakhll_market.User_View', verbose_name='بازدید کنندگان')),
            ],
            options={
                'verbose_name': 'بازدید حجره',
                'verbose_name_plural': 'بازدید حجره ها',
                'ordering': ('id',),
            },
        ),
    ]
