# Generated by Django 2.2.6 on 2020-04-21 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0048_auto_20200407_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id',), 'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصولات'},
        ),
        migrations.CreateModel(
            name='ShopComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.BooleanField(choices=[(True, 'مثبت'), (False, 'منفی')], default=True, verbose_name='نوع نظر')),
                ('Description', models.TextField(verbose_name='توضیخات نظر')),
                ('Available', models.BooleanField(default=False, verbose_name='وضعیت انتشار نظر')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')),
                ('FK_Like', models.ManyToManyField(blank=True, related_name='ShoComment_Like', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده')),
                ('FK_Pater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShoComment_Pater', to='nakhll_market.ShopComment', verbose_name='ریپلای شده')),
                ('FK_Shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shop_Comment', to='nakhll_market.Shop', verbose_name='حجره')),
                ('FK_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShoComment_Accept', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('FK_UserAdder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_ShoComment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر حجره',
                'verbose_name_plural': 'نظرات حجره',
                'ordering': ('id',),
            },
        ),
    ]
