# Generated by Django 2.2.6 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0051_auto_20200423_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Height_With_Packaging',
            field=models.CharField(default='0', max_length=4, verbose_name='ارتفاع محصول با بسته بندی (سانتی متر('),
        ),
        migrations.AlterField(
            model_name='product',
            name='Length_With_Packaging',
            field=models.CharField(default='0', max_length=4, verbose_name='طول محصول با بسته بندی (سانتی متر('),
        ),
        migrations.AlterField(
            model_name='product',
            name='Net_Weight',
            field=models.CharField(default='0', max_length=6, verbose_name='وزن محصول خالص (گرم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Packing_Weight',
            field=models.CharField(default='0', max_length=5, verbose_name='وزن محصول بسته بندی (گرم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Width_With_Packaging',
            field=models.CharField(default='0', max_length=4, verbose_name='عرض محصول با بسته بندی (سانتی متر('),
        ),
    ]
