# Generated by Django 2.2.6 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0052_auto_20200425_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Net_Weight',
            field=models.CharField(default='0', max_length=6, verbose_name='وزن خالص محصول (گرم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Packing_Weight',
            field=models.CharField(default='0', max_length=5, verbose_name='وزن بسته بندی محصول (گرم)'),
        ),
    ]
