# Generated by Django 2.2.6 on 2020-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0053_auto_20200425_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Packing_Weight',
        ),
        migrations.AddField(
            model_name='product',
            name='Weight_With_Packing',
            field=models.CharField(default='0', max_length=6, verbose_name='وزن محصول با بسته بندی (گرم)'),
        ),
    ]
