# Generated by Django 2.2.6 on 2020-04-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0054_auto_20200426_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Inventory',
            field=models.IntegerField(default=5, verbose_name='میزان موجودی از این کالا در انبار'),
        ),
    ]
