# Generated by Django 2.2.6 on 2020-05-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0056_auto_20200502_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmovie',
            old_name='Edite',
            new_name='Edit',
        ),
    ]
