# Generated by Django 2.2.6 on 2020-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0057_auto_20200506_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='Available',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='DateCreate',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='DateUpdate',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='Slug',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='Title',
            field=models.CharField(max_length=300, verbose_name='عنوان ویژگی'),
        ),
    ]
