# Generated by Django 2.2.6 on 2020-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0059_attrprice_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_view',
            name='User_Ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='آدرس ای پی'),
        ),
    ]
