# Generated by Django 2.2.6 on 2020-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0060_auto_20200512_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbanner',
            name='Title',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب روی بنر'),
        ),
    ]
