# Generated by Django 2.2.6 on 2020-06-27 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0061_auto_20200615_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Point',
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('FK_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_user', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیاز ها',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='FK_Points',
            field=models.ManyToManyField(blank=True, related_name='User_Points', to='nakhll_market.UserPoint', verbose_name='امتیاز ها'),
        ),
    ]
