# Generated by Django 2.2.6 on 2020-07-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0062_auto_20200627_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbanner',
            name='Title',
            field=models.CharField(max_length=100, null=True, verbose_name='برچسب روی بنر'),
        ),
    ]
