# Generated by Django 2.2.6 on 2020-08-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0063_auto_20200730_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopbanner',
            options={'ordering': ('id',), 'verbose_name': 'بنر حجره', 'verbose_name_plural': 'بنر حجره ها'},
        ),
    ]
