# Generated by Django 2.2.6 on 2020-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0064_auto_20200824_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptinalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='عنوان ویژگی')),
                ('Type', models.CharField(choices=[('0', 'تک انتخابی'), ('1', 'چند انتخابی')], max_length=1, verbose_name='نوع انتخابی')),
                ('Status', models.BooleanField(choices=[(True, 'اجباری'), (False, 'انتخابی')], default=False, verbose_name='وضعیت انتخاب')),
                ('Detail', models.FileField(null=True, upload_to='media/Json/OptinalAttribute/', verbose_name='جزیئات')),
                ('Available', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=True, verbose_name='وضعیت نمایش')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=True, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'ویژگی انتخابی',
                'verbose_name_plural': 'ویژگی های انتخابی',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='FK_OptinalAttribute',
            field=models.ManyToManyField(blank=True, related_name='product_optional_attribute', to='nakhll_market.OptinalAttribute', verbose_name='ویژگی های انتخابی'),
        ),
    ]
