# Generated by Django 2.2.6 on 2020-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0065_auto_20200905_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optinalattribute',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار'),
        ),
    ]
