# Generated by Django 2.2.6 on 2020-09-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0067_auto_20200913_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optinalattribute',
            name='Detail',
        ),
    ]
