# Generated by Django 2.2.6 on 2020-09-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0068_remove_optinalattribute_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=255, verbose_name='عنوان')),
                ('Price', models.CharField(max_length=15, verbose_name='قیمت محصول')),
                ('Weight', models.CharField(default='0', max_length=6, verbose_name='وزن محصول با بسته بندی (گرم)')),
                ('Length', models.CharField(default='0', max_length=4, verbose_name='طول محصول با بسته بندی (سانتی متر(')),
                ('Width', models.CharField(default='0', max_length=4, verbose_name='عرض محصول با بسته بندی (سانتی متر(')),
                ('Height', models.CharField(default='0', max_length=4, verbose_name='ارتفاع محصول با بسته بندی (سانتی متر(')),
                ('Inventory', models.IntegerField(default=0, verbose_name='موجودی')),
                ('Status', models.CharField(choices=[('1', 'آماده در انبار'), ('2', 'تولید بعد از سفارش'), ('3', 'سفارشی سازی فروش'), ('4', 'موجود نیست')], max_length=1, verbose_name='وضعیت محصول')),
            ],
            options={
                'verbose_name': 'جزئیات',
                'verbose_name_plural': 'جزئیات ها',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='optinalattribute',
            name='FK_Details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_attrinute_details', to='nakhll_market.Details', verbose_name='جزئیات'),
        ),
    ]
