# Generated by Django 2.2.6 on 2020-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0069_auto_20200930_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optinalattribute',
            name='FK_Details',
        ),
        migrations.AddField(
            model_name='optinalattribute',
            name='FK_Details',
            field=models.ManyToManyField(blank=True, related_name='optional_attrinute_details', to='nakhll_market.Details', verbose_name='جزئیات'),
        ),
    ]
