# Generated by Django 2.2.6 on 2020-10-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0071_auto_20201010_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Bio',
            field=models.TextField(blank=True, verbose_name='معرفی محصول'),
        ),
    ]
