# Generated by Django 2.2.6 on 2020-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0073_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
