# Generated by Django 2.2.6 on 2020-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0074_auto_20201217_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='entries_message',
            field=models.CharField(max_length=255),
        ),
    ]
