# Generated by Django 2.2.6 on 2020-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0075_auto_20201217_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
