# Generated by Django 2.2.6 on 2021-01-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0076_auto_20201224_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
