# Generated by Django 2.2.6 on 2021-01-06 21:01

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0077_delete_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonevalid',
            name='Date',
            field=django_jalali.db.models.jDateField(auto_now=True, null=True, verbose_name='تاریخ'),
        ),
    ]
