# Generated by Django 2.2.6 on 2021-01-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0078_auto_20210107_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserphoneValid',
        ),
    ]
