# Generated by Django 3.1.5 on 2021-01-26 10:34

from django.db import migrations, models
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0079_delete_userphonevalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ImageNationalCard',
            field=models.ImageField(blank=True, null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/NationalCard/'), verbose_name='عکس کارت ملی'),
        ),
    ]
