# Generated by Django 3.1.5 on 2021-02-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0081_auto_20210206_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazing_product', to='nakhll_market.product', verbose_name='محصول شگفت انگیز')),
            ],
            options={
                'verbose_name': 'شگفت انگیز',
                'verbose_name_plural': 'شگفت انگیزان',
                'ordering': ('id',),
            },
        ),
    ]
