# Generated by Django 3.1.5 on 2021-02-10 23:23

import django.contrib.postgres.fields
from django.db import migrations, models
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0082_amazingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/Shop/Document/'), verbose_name='عکس جدید حجره'), blank=True, default=list, size=None),
        ),
    ]
