# Generated by Django 3.0.5 on 2021-03-12 16:41

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0084_auto_20210307_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BrithDay',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
