# Generated by Django 3.1.6 on 2021-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0085_auto_20210508_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcity',
            name='code',
            field=models.IntegerField(verbose_name='کد شهرستان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(verbose_name='کد شهر'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.IntegerField(verbose_name='کد استان'),
        ),
    ]
