# Generated by Django 3.1.6 on 2021-05-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0086_auto_20210510_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
