# Generated by Django 3.1.6 on 2021-05-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0087_delete_newsletters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
