# Generated by Django 3.1.6 on 2021-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0088_auto_20210319_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='discount',
            field=models.BigIntegerField(default=0, verbose_name='تخفیف محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(default=0, verbose_name='تخفیف محصول'),
        ),
    ]
