# Generated by Django 3.1.6 on 2021-03-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0088_auto_20210319_2019'),
        ('nakhll_market', '0088_auto_20210319_2112'),
    ]

    operations = [
    ]
