# Generated by Django 3.1.6 on 2021-05-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0088_delete_voting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopViews',
        ),
    ]
