# Generated by Django 3.1.6 on 2021-05-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0089_delete_shopviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageViews',
        ),
    ]
