# Generated by Django 3.1.6 on 2021-05-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0090_delete_pageviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date_View',
        ),
    ]
