# Generated by Django 3.1.6 on 2021-03-23 07:24

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0090_auto_20210323_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='DisProduct',
            field=models.BigIntegerField(default=0, verbose_name='مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='DisProduct',
            field=models.BigIntegerField(default=0, verbose_name='مقدار تخفیف'),
        ),
        
    ]
