# Generated by Django 3.1.6 on 2021-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0090_fill_discount_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='default',
            field=models.BooleanField(default=False, verbose_name='عکس اصلی محصول'),
        ),
    ]
