# Generated by Django 3.1.6 on 2021-05-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0091_delete_date_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_View',
        ),
    ]
