# Generated by Django 3.1.6 on 2021-03-23 07:42

from django.db import migrations
from nakhll_market.models import Product


def make_DisProduct(apps, schema_editor):
    pro=Product.objects.exclude(OldPrice='0')
    for p in pro:
        p.DisProduct=p.OldPrice -p.Price
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0091_auto_20210323_1154'),
    ]

    operations = [
        migrations.RunPython(make_DisProduct),
    ]
