# Generated by Django 3.1.6 on 2021-03-23 21:45

from django.db import migrations, models
from nakhll_market.models import Product, ProductBanner

def move_image(apps, schema_editor):
    products = Product.objects.all()
    for product in products:
        product.Product_Banner.add(
            ProductBanner.objects.create(
                Title=product.Title,
                Image=product.Image,
                NewImage=product.NewImage,
                Publish=True,
                default=True,
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0091_productbanner_default'),
    ]

    operations = [
        migrations.RunPython(move_image),
    ]
