# Generated by Django 3.1.6 on 2021-05-10 11:10

from django.db import migrations, models
from nakhll_market.models import City

def central_to_big_city(apps, schema_editor):
    cities = City.objects.filter(name='مرکزی')
    for city in cities:
        city.name = city.big_city.name
        city.save()

class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0093_auto_20210602_1301'),
    ]

    operations = [
        migrations.RunPython(central_to_big_city, migrations.RunPython.noop),
    ]
