# Generated by Django 3.1.6 on 2021-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0094_city_central_to_bigcity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Type',
            field=models.BooleanField(choices=[(False, 'منفی'), (True, 'مثبت')], default=True, verbose_name='نوع نظر'),
        ),
    ]
