# Generated by Django 3.1.6 on 2021-06-28 11:25

from django.db import migrations, models
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0095_auto_20210612_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ImageNationalCardUnverified',
            field=models.ImageField(blank=True, null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/NationalCardUnverified/'), verbose_name='عکس کارت ملی تایید نشده'),
        ),
    ]
