# Generated by Django 3.1.6 on 2021-07-08 09:02

from django.db import migrations, models
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0096_profile_imagenationalcardunverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ImageNationalCardUnverified',
            field=models.ImageField(blank=True, null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/NationalCard/'), verbose_name='عکس کارت ملی تایید نشده'),
        ),
    ]
