# Generated by Django 3.1.6 on 2021-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0097_auto_20210708_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PreparationDays',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='زمان آماده\u200cسازی'),
        ),
    ]
