# Generated by Django 3.1.6 on 2021-07-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0099_dashboardbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, help_text='آی\u200cدی تلگرام بدون نام سایت', max_length=100, null=True, verbose_name='تلگرام')),
                ('instagram', models.CharField(blank=True, help_text='آی\u200cدی اینستاگرام بدون نام سایت', max_length=100, null=True, verbose_name='اینستاگرام')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='nakhll_market.shop', verbose_name='حجره')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی حجره',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی حجره',
            },
        ),
        migrations.CreateModel(
            name='ShopBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, help_text='شماره شبا بدون IR', max_length=24, null=True, verbose_name='شماره شبا')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='صاحب حساب')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='nakhll_market.shop', verbose_name='حجره')),
            ],
            options={
                'verbose_name': 'حساب بانکی حجره',
                'verbose_name_plural': 'حساب\u200cهای حجره',
            },
        ),
    ]
