# Generated by Django 3.1.6 on 2021-07-19 14:04

from django.db import migrations, models
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0100_shopbankaccount_shopsocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbankaccount',
            name='iban',
            field=models.CharField(blank=True, help_text='شماره شبا بدون IR', max_length=24, null=True, validators=[nakhll_market.models.iban_validator], verbose_name='شماره شبا'),
        ),
    ]
