# Generated by Django 3.1.6 on 2021-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0101_auto_20210719_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='show_contanct_info',
            field=models.BooleanField(default=False, verbose_name='نمایش اطلاعات تماس حجره'),
        ),
    ]
