# Generated by Django 3.1.6 on 2021-07-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0102_shop_show_contanct_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='show_contanct_info',
            new_name='show_contact_info',
        ),
    ]
