# Generated by Django 3.1.6 on 2021-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0104_auto_20210720_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='شناسه حجره'),
        ),
    ]
