# Generated by Django 3.1.6 on 2021-08-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0105_auto_20210722_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='شناسه محصول'),
        ),
    ]
