# Generated by Django 3.1.6 on 2021-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0106_auto_20210826_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_range_cities',
            field=models.ManyToManyField(related_name='products', to='nakhll_market.City', verbose_name='شهرهای قابل ارسال'),
        ),
    ]
