# Generated by Django 3.1.6 on 2021-09-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0106_auto_20210806_1748'),
        ('nakhll_market', '0108_auto_20210918_1650'),
    ]

    operations = [
    ]
