# Generated by Django 3.1.6 on 2021-09-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0110_auto_20210929_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_advertisement',
            field=models.BooleanField(default=False, verbose_name='آگهی'),
        ),
    ]
