# Generated by Django 3.1.6 on 2021-09-30 23:20

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0111_product_is_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.IntegerField(choices=[(1, 'بنر'), (2, 'کارت محصول')], default=1, verbose_name='نوع برنامه بندی')),
                ('data', models.URLField(max_length=255, null=True, verbose_name='داده ها')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=127, null=True, verbose_name='زیر عنوان')),
                ('url', models.URLField(max_length=100, null=True, verbose_name='لینک')),
                ('background_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='رنگ پس زمینه')),
                ('image', models.ImageField(null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/LandingPage/Schema/'), verbose_name='عکس')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('publish_status', models.CharField(choices=[('pub', 'منتشر شده'), ('prv', 'پیش\u200cنمایش')], default='pub', max_length=3)),
                ('staff_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_schemas', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'برنامه بندی صفحه اول',
                'verbose_name_plural': 'برنامه بندی صفحه اول',
            },
        ),
    ]
