# Generated by Django 3.1.6 on 2021-09-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0112_landingpageschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageschema',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
