# Generated by Django 3.1.6 on 2021-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0113_landingpageschema_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageschema',
            name='data',
            field=models.URLField(max_length=255, verbose_name='داده ها'),
        ),
    ]
