# Generated by Django 3.1.6 on 2021-10-01 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0114_auto_20211001_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageschema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nakhll_market.models.PathAndRename('media/Pictures/LandingPage/Schema/'), verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='landingpageschema',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_schemas', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
        migrations.AlterField(
            model_name='landingpageschema',
            name='subtitle',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='landingpageschema',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='landingpageschema',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='لینک'),
        ),
    ]
