# Generated by Django 3.1.6 on 2021-10-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0115_auto_20211001_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageschema',
            name='is_mobile',
            field=models.BooleanField(default=True, verbose_name='دستگاه موبایل است؟'),
        ),
        migrations.AlterField(
            model_name='landingpageschema',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'اسلایدر'), (2, '1 بنر'), (3, '2 بنر'), (4, '3 بنر'), (5, '4 بنر'), (6, 'ردیف محصول'), (7, 'ردیف محصول شگفت انگیز')], default=2, verbose_name='نوع برنامه بندی'),
        ),
        migrations.CreateModel(
            name='ShopPageSchema',
            fields=[
                ('landingpageschema_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nakhll_market.landingpageschema')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_page_schemas', to='nakhll_market.shop', verbose_name='فروشگاه')),
            ],
            bases=('nakhll_market.landingpageschema',),
        ),
    ]
