# Generated by Django 3.1.6 on 2021-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0116_auto_20211005_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_advertisement',
            field=models.BooleanField(default=False, null=True, verbose_name='آگهی'),
        ),
    ]
