# Generated by Django 3.1.6 on 2021-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0116_auto_20211005_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpageschema',
            name='is_mobile',
        ),
        migrations.AddField(
            model_name='landingpageschema',
            name='device',
            field=models.CharField(choices=[('mob', 'موبایل'), ('des', 'دسکتاپ'), ('tab', 'تبلت'), ('all', 'همه')], default='all', max_length=3, verbose_name='مخصوص چه دستگاهی است؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='بارکد'),
        ),
    ]
