# Generated by Django 3.1.6 on 2021-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0117_auto_20211009_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='has_product_group_import_permission',
            field=models.BooleanField(default=False, verbose_name='حجره دسترسی ایجاد و ویرایش محصول به صورت گروهی با استفاده از اکسل دارد؟'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_landing',
            field=models.BooleanField(default=False, verbose_name='صفحه حجره لندیگ است؟'),
        ),
    ]
