# Generated by Django 3.1.6 on 2021-10-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0118_auto_20211009_1216'),
        ('nakhll_market', '0117_auto_20211006_1206'),
    ]

    operations = [
    ]
