# Generated by Django 3.1.6 on 2021-10-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0120_auto_20211009_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='بارکد'),
        ),
        migrations.AddField(
            model_name='shop',
            name='has_product_group_add_edit_permission',
            field=models.BooleanField(default=False, verbose_name='حجره دسترسی ایجاد و ویرایش محصول به صورت گروهی با استفاده از اکسل دارد؟'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_landing',
            field=models.BooleanField(default=False, verbose_name='صفحه حجره لندینگ است؟'),
        ),
    ]
