# Generated by Django 3.1.6 on 2021-10-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0121_auto_20211009_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageschema',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'اسلایدر'), (2, '1 بنر'), (3, '2 بنر'), (4, '3 بنر'), (5, '4 بنر'), (6, 'ردیف محصول'), (7, 'ردیف محصول شگفت انگیز'), (8, 'آیکن')], default=2, verbose_name='نوع برنامه بندی'),
        ),
    ]
