# Generated by Django 3.1.6 on 2021-10-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0109_auto_20211003_1246'),
        ('nakhll_market', '0122_auto_20211010_1415'),
    ]

    operations = [
    ]
