# Generated by Django 3.1.6 on 2021-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0123_merge_20211014_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_range_cities',
            field=models.ManyToManyField(blank=True, related_name='products', to='nakhll_market.City', verbose_name='شهرهای قابل ارسال'),
        ),
    ]
