# Generated by Django 3.1.6 on 2021-10-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0124_auto_20211018_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppageschema',
            options={'verbose_name': 'برنامه بندی صفحه حجره دار', 'verbose_name_plural': 'برنامه بندی صفحه حجره دار'},
        ),
    ]
