# Generated by Django 3.1.6 on 2021-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0125_auto_20211019_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageschema',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک'),
        ),
    ]
