# Generated by Django 3.1.6 on 2021-10-25 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0126_auto_20211023_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('ID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('Title', models.CharField(db_index=True, max_length=200, verbose_name='نام محصول')),
                ('Slug', models.SlugField(allow_unicode=True, max_length=200, verbose_name='شناسه محصول')),
                ('Story', models.TextField(blank=True, verbose_name='داستان محصول')),
                ('Description', models.TextField(blank=True, verbose_name='درباره محصول')),
                ('Bio', models.TextField(blank=True, verbose_name='معرفی محصول')),
                ('Image', models.TextField(help_text='عکس محصول خود را اینجا بارگذاری کنید', max_length=100, verbose_name='عکس محصول')),
                ('NewImage', models.TextField(blank=True, max_length=100, null=True, verbose_name='عکس جدید حجره')),
                ('Catalog', models.TextField(blank=True, help_text='کاتالوگ محصول خود را اینجا وارد کنید', max_length=100, null=True, verbose_name='کاتالوگ محصول')),
                ('Price', models.BigIntegerField(verbose_name='قیمت محصول')),
                ('OldPrice', models.BigIntegerField(default=0, verbose_name='قیمت حذف محصول')),
                ('Net_Weight', models.CharField(default='0', max_length=6, verbose_name='وزن خالص محصول (گرم)')),
                ('Weight_With_Packing', models.CharField(default='0', max_length=6, verbose_name='وزن محصول با بسته بندی (گرم)')),
                ('Length_With_Packaging', models.CharField(default='0', max_length=4, verbose_name='طول محصول با بسته بندی (سانتی متر(')),
                ('Width_With_Packaging', models.CharField(default='0', max_length=4, verbose_name='عرض محصول با بسته بندی (سانتی متر(')),
                ('Height_With_Packaging', models.CharField(default='0', max_length=4, verbose_name='ارتفاع محصول با بسته بندی (سانتی متر(')),
                ('Inventory', models.IntegerField(default=5, verbose_name='میزان موجودی از این کالا در انبار')),
                ('PostRangeType', models.CharField(choices=[('1', 'سراسر کشور'), ('2', 'استانی'), ('3', 'شهرستانی'), ('4', 'شهری')], default='1', help_text='محدوده ارسال را بر اساس تایپ های مشخص شده، تعیین کنید.', max_length=1, verbose_name='محدوده ارسال محصولات')),
                ('Status', models.CharField(choices=[('1', 'آماده در انبار'), ('2', 'تولید بعد از سفارش'), ('3', 'سفارشی سازی فروش'), ('4', 'موجود نیست')], max_length=1, verbose_name='وضعیت فروش')),
                ('DateCreate', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بارگذاری محصول')),
                ('DateUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی محصول')),
                ('Edite', models.BooleanField(choices=[(True, 'در حال بررسی تغییرات'), (False, 'تغییری اعمال شده است')], default=False, verbose_name='وضعیت ویرایش محصول')),
                ('Available', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=True, verbose_name='وضعیت بارگذاری محصول')),
                ('Publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار محصول')),
                ('PreparationDays', models.PositiveSmallIntegerField(null=True, verbose_name='زمان آماده\u200cسازی')),
                ('is_advertisement', models.BooleanField(default=False, null=True, verbose_name='آگهی')),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, verbose_name='بارکد')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('FK_Shop', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nakhll_market.shop', verbose_name='حجره')),
                ('FK_SubMarket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nakhll_market.submarket', verbose_name='نام راسته')),
                ('FK_User', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical محصول',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
