# Generated by Django 3.1.6 on 2021-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0130_auto_20211102_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
