# Generated by Django 3.1.6 on 2021-12-01 10:54

from django.db import migrations, models
import django.db.models.deletion
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0132_auto_20211108_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=nakhll_market.models.PathAndRename('media/Pictures/User/UploadedImages/'), verbose_name='تصویر بارگذاری شده')),
                ('publish', models.BooleanField(default=True, verbose_name='منتشر شده?')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='nakhll_market.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تصویر بارگذاری شده کاربر',
                'verbose_name_plural': 'تصویر بارگذاری شده کاربر',
            },
        ),
    ]
