# Generated by Django 3.1.6 on 2021-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0134_auto_20211205_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_description',
            field=models.TextField(blank=True, help_text='توضیحات در مورد هشدار', null=True, verbose_name='توضیحات'),
        ),
    ]
