# Generated by Django 3.1.6 on 2021-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0135_auto_20211205_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Description',
            field=models.TextField(blank=True, help_text='در صورت عدم پذیرش تغییرات انجام شده، لطفا دلایل خودت را اینجا وارد نمایید.', null=True, verbose_name='توضیحات'),
        ),
    ]
