# Generated by Django 3.1.6 on 2022-01-05 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nakhll_market.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0136_auto_20220105_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(max_length=100, unique=True, verbose_name='نام صفحه')),
                ('status', models.IntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال')], default=1, verbose_name='وضعیت')),
                ('page_data', models.TextField(blank=True, null=True, verbose_name='داده\u200cهای صفحه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'صفحه فرود',
                'verbose_name_plural': 'صفحه فرود',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=nakhll_market.models.PathAndRename('media/Pictures/Landing/'), verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nakhll_market.landingpage', verbose_name='صفحه فرود')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_images', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'تصویر صفحه فرود',
                'verbose_name_plural': 'تصویر صفحه فرود',
            },
        ),
    ]
