# Generated by Django 3.1.6 on 2022-01-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0137_landingimage_landingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='page_slug',
            new_name='slug',
        ),
    ]
