# Generated by Django 3.1.6 on 2022-01-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0138_auto_20220105_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='in_campaign',
            field=models.BooleanField(default=False, verbose_name='در کمپین؟'),
        ),
    ]
