# Generated by Django 3.1.6 on 2022-02-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_auto_20220118_1044'),
        ('nakhll_market', '0140_auto_20220123_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCategory',
            new_name='Category',
        ),
    ]
