# Generated by Django 3.1.6 on 2022-02-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0141_auto_20220205_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='new_category',
            field=models.ForeignKey(blank=True, db_column='category_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nakhll_market.category', verbose_name='دسته بندی جدید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='nakhll_market.category', verbose_name='دسته بندی جدید'),
        ),
    ]
