# Generated by Django 3.1.6 on 2022-02-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0142_auto_20220205_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='new_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='new_category',
            new_name='category',
        ),
    ]
