# Generated by Django 3.1.6 on 2022-05-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0145_manipulate_nullable_data'),
    ]

    operations = [
       migrations.AlterField(
            model_name='product',
            name='FK_Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ShopProduct', to='nakhll_market.shop', verbose_name='حجره'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='FK_ShopManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ShopManager', to='auth.user', verbose_name='حجره دار'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='عنوان حجره'),
        ),
    ]
