# Generated by Django 3.2.12 on 2022-05-18 10:29

from django.db import migrations, models


def transfer_data(apps, schema_editor):
    '''transfer state, city and big city to new fields'''
    Shop = apps.get_model("nakhll_market", "Shop")
    for shop in Shop.objects.all():
        shop.state_old = shop.State
        shop.city_old = shop.City
        shop.big_city_old = shop.BigCity
        shop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0146_auto_20220501_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='big_city_old',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='city_old',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='state_old',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='BigCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='استان'),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
