# Generated by Django 3.2.12 on 2022-05-22 15:28

from django.db import migrations, models
from django.db.models import Count


def create_unique_product_title(title):
    '''create unique product title'''
    num = 0

    def unique_title(title):
        nonlocal num
        while True:
            if num == 0:
                num += 1
                yield title
            else:
                num += 1
                yield f'{title} ({num})'

    return unique_title(title)


def modify_repeated_product_title(apps, schema_editor):
    '''modify repeated product title in same shop'''
    Product = apps.get_model("nakhll_market", "Product")
    repeated_title_products = Product.objects.order_by().values(
        'FK_Shop_id', 'Title').annotate(count=Count('*')).filter(count__gt=1)
    for product in repeated_title_products:
        title_generator = create_unique_product_title(product['Title'])
        products = Product.objects.filter(
            FK_Shop_id=product['FK_Shop_id'],
            Title=product['Title'])
        for _product in products:
            _product.Title = next(title_generator)
            _product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0148_auto_20220518_1500'),
    ]

    operations = [
        migrations.RunPython(
            modify_repeated_product_title,
            migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(
                fields=(
                    'Title',
                    'FK_Shop_id'),
                name='unique_shop_product_title'),
        ),
    ]
