# Generated by Django 3.2.12 on 2022-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0148_alter_product_category'),
        ('nakhll_market', '0149_product_unique_shop_product_title'),
    ]

    operations = [
    ]
