# Generated by Django 3.2.12 on 2022-05-22 15:28

from django.db import migrations


def make_dummy_category_unavailable(apps, schema_editor):
    Category = apps.get_model("nakhll_market", "Category")
    Category.objects.filter(name='dummy').update(available=False)


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0150_merge_20220525_1423'),
    ]

    operations = [
        migrations.RunPython(
            make_dummy_category_unavailable,
            migrations.RunPython.noop)
    ]
