# Generated by Django 3.2.12 on 2022-06-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0151_make_dummy_category_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'max_length': 'نام تگ باید کمتر از 127 کاراکتر باشد.'}, max_length=127, verbose_name='نام تگ'),
        ),
    ]
