# Generated by Django 3.2.12 on 2022-06-28 08:49

from django.db import migrations
import jdatetime


def clean_profile_birthday(apps, schema_editor):
    Profile = apps.get_model("nakhll_market", "Profile")
    for profile in Profile.objects.exclude(
            BrithDay=None).filter(
            BrithDay__lt='1300-01-01'):
        gregorian_date_time = profile.BrithDay.togregorian()
        jalali_date_time = jdatetime.datetime(
            gregorian_date_time.year,
            gregorian_date_time.month,
            gregorian_date_time.day)
        if jalali_date_time.year < 1300:
            profile.BrithDay = None
            profile.save()
        else:
            profile.BrithDay = jalali_date_time
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0152_alter_tag_name'),
    ]

    operations = [
        migrations.RunPython(
            clean_profile_birthday,
            migrations.RunPython.noop),
    ]
