# Generated by Django 3.2.14 on 2022-07-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0153_auto_20220628_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='aparat_video_script',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='اسکریپت ویدیو آپارات'),
        ),
        migrations.AddField(
            model_name='product',
            name='aparat_video_script',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='اسکریپت ویدیو آپارات'),
        ),
    ]
