# Generated by Django 3.2.12 on 2022-07-02 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0153_auto_20220628_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='UserReferenceCode',
            new_name='refer_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ReferenceCode',
        ),
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دعوت کننده به نخل'),
        ),
    ]
