# Generated by Django 3.2.14 on 2022-07-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0154_auto_20220719_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbanner',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب روی بنر'),
        ),
    ]
