# Generated by Django 3.2.14 on 2022-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0155_alter_productbanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=True, verbose_name='وضعیت انتشار محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Publish',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=True, verbose_name='وضعیت انتشار محصول'),
        ),
    ]
