# Generated by Django 3.2.14 on 2022-07-24 10:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0157_clean_price_and_old_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('Price', 0), _negated=True), name='check_price_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('OldPrice__gt', django.db.models.expressions.F('Price')), ('OldPrice', 0), _connector='OR'), name='price_is_greater_than_discounted_price'),
        ),
    ]
