# Generated by Django 3.2.14 on 2022-08-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0154_auto_20220702_1442'),
        ('nakhll_market', '0158_auto_20220724_1453'),
    ]

    operations = [
    ]
