# Generated by Django 3.2.14 on 2022-08-07 14:51

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0159_merge_0154_auto_20220702_1442_0158_auto_20220724_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_date_of_referral_link',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
