# Generated by Django 3.2.14 on 2022-08-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nakhll_market', '0160_profile_expiration_date_of_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دعوت کننده به نخل'),
        ),
    ]
