# Generated by Django 3.2.14 on 2022-09-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0161_alter_profile_referrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='refer_code',
        ),
    ]
