# Generated by Django 3.1.6 on 2021-09-05 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('url_redirector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='destination_url',
            field=models.URLField(default='https://nakhll.com/', verbose_name='آدرس مقصد'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='کد آدرس'),
        ),
    ]
