# Generated by Django 3.1.6 on 2021-09-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_redirector', '0002_auto_20210905_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
    ]
