# Generated by Django 3.2.12 on 2022-04-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0029_remove_invoice_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='InoviceProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoice.invoice',),
        ),
        migrations.CreateModel(
            name='InvoiceItemReport',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش محصولات فاکتور شده',
                'verbose_name_plural': 'گزارش محصولات فاکتور شده',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoice.invoiceitem',),
        ),
    ]
