# Generated by Django 3.1.6 on 2021-11-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nakhll_market', '0130_auto_20211102_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_permission_code_name', models.CharField(choices=[('landing', 'صفحه اصلی'), ('bulk_operation', 'عملیات دسته جمعی')], max_length=15, verbose_name='نام کد دسترسی')),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('1time', 'یک بار'), ('week', 'هفته'), ('month', 'ماه'), ('year', 'سال')], default='1time', max_length=5)),
                ('price_per_unit_without_discount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_per_unit_with_discount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('demo_days', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ویژگی فروشگاه',
                'verbose_name_plural': 'ویژگی فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopFeatureInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_paying', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='awaiting_paying', max_length=15, verbose_name='وضعیت')),
                ('bought_price_per_unit', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت خرید')),
                ('bought_unit', models.CharField(max_length=20, verbose_name='واحد خرید')),
                ('unit_count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('expire_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('payment_unique_id', models.BigIntegerField(blank=True, null=True, verbose_name='شماره درخواست پرداخت')),
                ('is_demo', models.BooleanField(default=False, verbose_name='دمو')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_shop_feature_items', to='shop.shopfeature', verbose_name='ویژگی فروشگاه')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_shop_feature_items', to='nakhll_market.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'فاکتور ویژگی فروشگاه',
                'verbose_name_plural': 'فاکتورهای ویژگی فروشگاه',
            },
        ),
    ]
