# Generated by Django 3.1.6 on 2021-11-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0130_auto_20211102_1627'),
        ('shop', '0003_auto_20211107_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10, verbose_name='وضعیت')),
                ('page_data', models.TextField(verbose_name='داده\u200cهای صفحه')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='nakhll_market.shop', verbose_name='حجره')),
            ],
            options={
                'verbose_name': 'صفحات فرود فروشگاه',
            },
        ),
    ]
