# Generated by Django 3.1.6 on 2022-01-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211107_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedurl',
            name='link',
            field=models.URLField(max_length=500, verbose_name='لینک'),
        ),
    ]
