# Generated by Django 3.1.6 on 2022-01-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopadvertisement'),
        ('shop', '0007_auto_20220105_1031'),
    ]

    operations = [
    ]
