# Generated by Django 3.1.6 on 2022-01-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_merge_20220109_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadvertisement',
            name='yektanet_status',
            field=models.IntegerField(choices=[(1, 'فعال'), (0, 'غیرفعال')], default=0, verbose_name='وضعیت تبلیغاتی یکتانت'),
        ),
    ]
