# Generated by Django 3.2.12 on 2022-04-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220110_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplanding',
            options={'verbose_name': 'صفحه فرود فروشگاه', 'verbose_name_plural': 'صفحات فرود فروشگاه'},
        ),
    ]
