# Generated by Django 3.1.6 on 2021-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_postpricesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='receiver_full_name',
            field=models.CharField(default='user_full_name', max_length=200, verbose_name='نام و نام خانوادگی گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_mobile_number',
            field=models.CharField(default='user_mobile', max_length=11, verbose_name='تلفن همراه گیرنده'),
            preserve_default=False,
        ),
    ]
