# Generated by Django 3.1.6 on 2021-10-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_auto_20210816_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='old_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
