# Generated by Django 3.1.6 on 2021-12-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_auto_20211218_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticunitconstraintparameter',
            name='max_package_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر ارزش بسته'),
        ),
        migrations.AlterField(
            model_name='logisticunitconstraintparameter',
            name='max_weight_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر وزن (گرم)'),
        ),
        migrations.AlterField(
            model_name='logisticunitconstraintparameter',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداقل قیمت'),
        ),
    ]
