# Generated by Django 3.1.6 on 2021-12-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0135_auto_20211205_1607'),
        ('logistic', '0010_auto_20211222_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticunit',
            name='shown_alone',
        ),
        migrations.AddField(
            model_name='logisticunit',
            name='is_default_logistic_unit',
            field=models.BooleanField(default=False, help_text='در صورت عدم نبود واحد ارسال دیگر، این واحد ارسال پیش فرض خواهد بود.', verbose_name='واحد پیش فرض ارسال؟'),
        ),
        migrations.AlterField(
            model_name='logisticunitconstraint',
            name='logistic_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_unit_constraints', to='logistic.logisticunit', verbose_name='واحد ارسال'),
        ),
        migrations.AlterField(
            model_name='shoplogisticunit',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_logistic_units', to='nakhll_market.shop', verbose_name='فروشگاه'),
        ),
    ]
