# Generated by Django 3.1.6 on 2021-12-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0011_auto_20211223_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticUnitGeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price_per_kilogram', models.PositiveIntegerField(default=0, verbose_name='قیمت به ازای هر کیلو (ریال)')),
                ('default_price_per_extra_kilogram', models.PositiveIntegerField(default=0, verbose_name='قیمت به ازای هر کیلو اضافه (ریال)')),
                ('maximum_price_per_kilogram', models.PositiveIntegerField(default=0, verbose_name='حداکثر قیمت به ازای هر کیلو (ریال)')),
                ('maximum_price_per_extra_kilogram', models.PositiveIntegerField(default=0, verbose_name='حداکثر قیمت به ازای هر کیلو اضافه (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات واحد ارسال',
                'verbose_name_plural': 'تنظیمات واحد ارسال',
            },
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraint',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraint',
            name='logistic_unit',
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraintparameter',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraintparameter',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraintparameter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='logisticunitconstraintparameter',
            name='products',
        ),
        migrations.RemoveField(
            model_name='logisticunitmetric',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shoplogisticunit',
            name='logistic_unit',
        ),
        migrations.RemoveField(
            model_name='shoplogisticunit',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shoplogisticunitconstraint',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='shoplogisticunitconstraint',
            name='shop_logistic_unit',
        ),
        migrations.RemoveField(
            model_name='shoplogisticunitmetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='shoplogisticunitmetric',
            name='shop_logistic_unit_constraint',
        ),
        migrations.DeleteModel(
            name='LogisticUnit',
        ),
        migrations.DeleteModel(
            name='LogisticUnitConstraint',
        ),
        migrations.DeleteModel(
            name='LogisticUnitConstraintParameter',
        ),
        migrations.DeleteModel(
            name='LogisticUnitMetric',
        ),
        migrations.DeleteModel(
            name='ShopLogisticUnit',
        ),
        migrations.DeleteModel(
            name='ShopLogisticUnitConstraint',
        ),
        migrations.DeleteModel(
            name='ShopLogisticUnitMetric',
        ),
    ]
