# Generated by Django 3.1.6 on 2021-12-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0135_auto_20211205_1607'),
        ('logistic', '0012_auto_20211226_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLogisticUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام واحد')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logistic/shop_logistic_units/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('is_publish', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_units', to='nakhll_market.shop', verbose_name='حجره')),
            ],
            options={
                'verbose_name': 'واحد ارسال فروشگاه',
                'verbose_name_plural': 'واحد ارسال فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopLogisticUnitConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='حداکثر وزن (کیلوگرم)')),
                ('min_weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='حداقل وزن (کیلوگرم)')),
                ('max_cart_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='حداکثر قیمت سبد خرید (ریال)')),
                ('min_cart_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='حداقل قیمت سبد خرید (ریال)')),
                ('max_cart_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='حداکثر تعداد سبد خرید')),
                ('min_cart_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='حداقل تعداد سبد خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('categories', models.ManyToManyField(related_name='logistic_unit_constraints', to='nakhll_market.NewCategory', verbose_name='دسته بندی ها')),
                ('cities', models.ManyToManyField(related_name='logistic_unit_constraints', to='nakhll_market.City', verbose_name='شهرها')),
                ('products', models.ManyToManyField(related_name='logistic_unit_constraints', to='nakhll_market.Product', verbose_name='محصولات')),
                ('shop_logistic_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint', to='logistic.shoplogisticunit', verbose_name='واحد ارسال')),
            ],
            options={
                'verbose_name': 'محدودیت واحد ارسال فروشگاه',
                'verbose_name_plural': 'محدودیت واحد ارسال فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopLogisticUnitCalculationMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kilogram', models.PositiveIntegerField(default=0, verbose_name='قیمت به ازای هر کیلو (ریال)')),
                ('price_per_extra_kilogram', models.PositiveIntegerField(default=0, verbose_name='قیمت به ازای هر کیلو اضافه (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('shop_logistic_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_metric', to='logistic.shoplogisticunit', verbose_name='واحد ارسال')),
            ],
            options={
                'verbose_name': 'پارامتر\u200c محاسبه واحد ارسال فروشگاه',
                'verbose_name_plural': 'پارامتر\u200c محاسبه واحد ارسال فروشگاه',
            },
        ),
    ]
