# Generated by Django 3.1.6 on 2021-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0135_auto_20211205_1607'),
        ('logistic', '0013_shoplogisticunit_shoplogisticunitcalculationmetric_shoplogisticunitconstraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplogisticunit',
            options={'ordering': ['-id'], 'verbose_name': 'واحد ارسال فروشگاه', 'verbose_name_plural': 'واحد ارسال فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='shoplogisticunitcalculationmetric',
            options={'ordering': ['-id'], 'verbose_name': 'پارامتر\u200c محاسبه واحد ارسال فروشگاه', 'verbose_name_plural': 'پارامتر\u200c محاسبه واحد ارسال فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='shoplogisticunitconstraint',
            options={'ordering': ['-id'], 'verbose_name': 'محدودیت واحد ارسال فروشگاه', 'verbose_name_plural': 'محدودیت واحد ارسال فروشگاه'},
        ),
        migrations.AlterField(
            model_name='shoplogisticunitconstraint',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='logistic_unit_constraints', to='nakhll_market.City', verbose_name='شهرها'),
        ),
    ]
