# Generated by Django 3.1.6 on 2021-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0135_auto_20211205_1607'),
        ('logistic', '0014_auto_20211227_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplogisticunitconstraint',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='logistic_unit_constraints', to='nakhll_market.NewCategory', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='shoplogisticunitconstraint',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='logistic_unit_constraints', to='nakhll_market.Product', verbose_name='محصولات'),
        ),
    ]
