# Generated by Django 3.1.6 on 2021-12-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0015_auto_20211227_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplogisticunit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/Pictures/logistic_unit/defaults', verbose_name='لوگو'),
        ),
    ]
