# Generated by Django 3.1.6 on 2022-01-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0016_auto_20211227_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplogisticunit',
            name='logo',
            field=models.ImageField(blank=True, default='static/Pictures/unkown_lu.png', null=True, upload_to='media/Pictures/logistic_unit/defaults', verbose_name='لوگو'),
        ),
    ]
