# Generated by Django 3.1.6 on 2022-01-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0018_auto_20220111_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplogisticunit',
            name='logo_type',
            field=models.IntegerField(choices=[(0, 'لوگوی شخصی'), (1, 'پست پیشتاز'), (2, 'پست سفارشی'), (3, 'پیک'), (4, 'پسکرایه'), (5, 'رایگان')], default=0, verbose_name='نوع لوگو'),
        ),
    ]
