# Generated by Django 3.1.6 on 2022-02-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_auto_20220118_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPriceSetting',
        ),
    ]
