# Generated by Django 3.2.12 on 2022-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0022_logisticunitgeneralsetting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticunitgeneralsetting',
            name='name',
            field=models.IntegerField(choices=[(0, 'پست پیشتاز'), (1, 'پست سفارشی')], default=0, unique=True, verbose_name='نوع ارسال پستی'),
        ),
    ]
