# Generated by Django 3.2.12 on 2022-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0023_alter_logisticunitgeneralsetting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticunitgeneralsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='logisticunitgeneralsetting',
            name='is_only_for_shop_city',
            field=models.BooleanField(default=False, verbose_name='فقط برای شهر حجره فعال می باشد'),
        ),
        migrations.AlterField(
            model_name='logisticunitgeneralsetting',
            name='name',
            field=models.IntegerField(choices=[(1, 'پست پیشتاز'), (2, 'پست سفارشی'), (3, 'پیک'), (4, 'پسکرایه'), (5, 'ارسال رایگان')], default=1, unique=True, verbose_name='نوع ارسال پستی'),
        ),
    ]
