# Generated by Django 3.1.6 on 2021-08-07 08:31

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nakhll_market', '0106_auto_20210806_1748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_unique_id', models.UUIDField(blank=True, null=True, verbose_name='شناسه کاربر مهمان')),
                ('status', models.CharField(choices=[('prog', 'در حال اجرا'), ('fact', 'بسته شده')], default='prog', max_length=4, verbose_name='وضعیت سبد خرید')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سبد خرید')),
                ('change_status_datetime', models.DateTimeField(null=True, verbose_name='تاریخ تغییر وضعیت سبد')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartTransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='cart.cart', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'ارسال سبد خرید',
                'verbose_name_plural': 'ارسال\u200cهای سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='تعداد')),
                ('added_datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن')),
                ('product_last_known_state', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='آیتم\u200cهای سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='nakhll_market.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'کالای سبد خرید',
                'verbose_name_plural': 'کالاهای سبد خرید',
            },
        ),
    ]
