# Generated by Django 3.1.6 on 2021-08-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='guest_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه کاربر مهمان'),
        ),
    ]
