# Generated by Django 3.1.6 on 2021-09-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210807_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_last_known_state',
            new_name='product_last_state',
        ),
        migrations.DeleteModel(
            name='CartTransmission',
        ),
    ]
