# Generated by Django 3.1.6 on 2021-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210912_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('running', 'در حال اجرا'), ('archived', 'بایگانی شده')], default='running', max_length=10, verbose_name='وضعیت سبد خرید'),
        ),
    ]
