# Generated by Django 3.1.6 on 2021-10-01 20:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20211001_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='old_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
