# Generated by Django 3.1.6 on 2021-10-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20211003_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='change_status_datetime',
        ),
    ]
