# Generated by Django 3.1.6 on 2022-02-09 09:30

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0021_delete_postpricesetting'),
        ('coupon', '0011_couponconstraint_cities'),
        ('cart', '0009_remove_cart_change_status_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='logistic.address', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='coupon.Coupon', verbose_name='کوپن ها'),
        ),
        migrations.AddField(
            model_name='cart',
            name='logistic_details',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='جزئیات واحد ارسال'),
        ),
    ]
