# Generated by Django 3.1.6 on 2022-02-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_list', '0002_auto_20220205_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='products',
        ),
    ]
