"""
Django settings for nakhll project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGIN = '/profile/dashboard/'

LOGOUT_REDIRECT_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = int(os.environ.get("DEBUG", default=0))

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a space between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ") 

COMPRESS_ENABLED = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'tinymce',
    'django_jalali',
    'admin_reorder',
    'nakhll_market',
    'Payment',
    'blog',
    'Ticketing',
    'restapi',
    'oauth2_provider',
    'rest_framework',
    'rest_framework.authtoken',
    'imagekit',
    'compressor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ADMIN_REORDER = (
    {'app': 'nakhll_market','models':(
        'nakhll_market.Pages',
        'nakhll_market.Profile',
        'nakhll_market.Market',
        'nakhll_market.SubMarket',
        'nakhll_market.Shop',
        'nakhll_market.Product',
        'nakhll_market.Category',
        'nakhll_market.Tag',
        'nakhll_market.Attribute',
        'nakhll_market.AttrPrice',
        'nakhll_market.Comment',
        'nakhll_market.Review',
        'nakhll_market.Message',
        'nakhll_market.Survey',
        'nakhll_market.Slider',
        'nakhll_market.Option_Meta',
        'nakhll_market.Alert',
        'nakhll_market.Newsletters',
    )},

    {'app': 'Payment', 'label': 'بخش مالی','models':(
        'Payment.Wallet',
        'Payment.Factor',
        'Payment.PostBarCode',
        'Payment.ManegerFactor',
        'Payment.Transaction',
        'Payment.Coupon',
        'Payment.Campaign',
        'Payment.Installment',
        'Payment.Invitation',
    )},
    
    {'app': 'blog', 'label': 'وبلاگ','models':(
        'blog.CategoryBlog',
        'blog.PostBlog',
        'blog.VendorStory',
        'blog.CommentPost',
    )},

    {'app': 'Ticketing', 'label': 'بخش پشتیبانی و گزارشات','models':(
        'Ticketing.Ticketing',
    )},

    {'app': 'auth','label':'کاربران و دسترسی ها'},
    
    {'app': 'sites','label':'دسترسی SiteMap'},
    
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

ROOT_URLCONF = 'nakhll.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'nakhll.wsgi.application'
IMAGEKIT_CACHEFILE_DIR = 'media/CACHE/images'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


PERSISTENT_STORAGE = "/mnt/shared-volume"
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nakhlldb',
#         'USER': 'root',
#         'PASSWORD': 'mmad9132412982',
#         'HOST' : 'nakhlldb',
#         'PORT' : '3306',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.mysql"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "3306"),
    }
}


#  Liara DB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'awesome_yalow',
#         'USER': 'root',
#         'PASSWORD': 'sS2bfePdX99iWttgn2PiTCzP',
#         'HOST' : 's11.liara.ir',
#         'PORT' : '34522',
#     }
# }

# PythonAnyWhere DB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'markrahimi$nakhll_db',
#         'USER': 'markrahimi',
#         'PASSWORD': 'moeintaheri@7677',
#         'HOST': 'markrahimi.mysql.pythonanywhere-services.com',

#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nakhll_analyze',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST' : '127.0.0.1',
#         'PORT' : '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, '')
MEDIA_URL = '/'

SESSION_COOKIE_AGE = 216000

CART_SESSION_ID = 'cart'

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
    'OAUTH_BACKEND_CLASS' : 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    'ACCESS_TOKEN_EXPIRE_SECONDS': 86400,
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}