# Generated by Django 3.1.6 on 2021-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_unique_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='شماره درخواست پرداخت'),
        ),
    ]
