# Generated by Django 3.1.6 on 2021-09-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210912_1617'),
        ('invoice', '0003_invoice_payment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='cart.cart', verbose_name='سبد خرید'),
        ),
    ]
