# Generated by Django 3.1.6 on 2021-10-02 07:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20210930_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='FctorNumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره فاکتور'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='address_json',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='آدرس ثبت شده نهایی'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='old_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('awaiting_paying', 'در انتظار پرداخت'), ('paying', 'در حال پرداخت'), ('wait_store_approv', 'در انتظار تأیید فروشگاه'), ('preparing_product', 'در حال آماده سازی'), ('wait_customer_approv', 'در انتظار تأیید مشتری'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='awaiting_paying', max_length=20, verbose_name='وضعیت فاکتور'),
        ),
    ]
