# Generated by Django 3.1.6 on 2021-10-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20211002_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='FctorNumber',
            new_name='FactorNumber',
        ),
    ]
