# Generated by Django 3.1.6 on 2021-10-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0115_auto_20211001_0335'),
        ('invoice', '0009_auto_20211003_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='final_coupon_price',
            new_name='coupon_price',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='final_invoice_price',
            new_name='invoice_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='final_logistic_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='source_module',
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('awaiting_paying', 'در انتظار پرداخت'), ('wait_store_approv', 'در انتظار تأیید فروشگاه'), ('preparing_product', 'در حال آماده سازی'), ('wait_customer_approv', 'در انتظار تأیید مشتری'), ('wait_store_checkout', 'در انتظار تسویه با فروشگاه'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='awaiting_paying', max_length=20, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=500, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت قبلی')),
                ('weight', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='وزن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='invoice_items', verbose_name='تصویر')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='invoice_items', verbose_name='تصویر کوچک')),
                ('shop_name', models.CharField(max_length=500, verbose_name='نام فروشگاه')),
                ('added_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('shop_confirmed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید فروشگاه')),
                ('post_type', models.CharField(choices=[('irpost', 'شرکت پست'), ('incity', 'درون شهری')], default='irpost', max_length=20, verbose_name='نوع پست')),
                ('post_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پستی')),
                ('user_confirm_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید کاربر')),
                ('user_confirm_status', models.CharField(blank=True, choices=[('awaiting_confirm', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], max_length=20, null=True, verbose_name='وضعیت تایید کاربر')),
                ('user_confirm_comment', models.TextField(blank=True, null=True, verbose_name='توضیحات تایید کاربر')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice', verbose_name='فاکتور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='nakhll_market.product')),
            ],
        ),
    ]
