# Generated by Django 3.1.6 on 2021-10-03 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0011_auto_20211003_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_weight_gram',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن نهایی (گرم)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=72, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
