# Generated by Django 3.1.6 on 2021-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20211003_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=0, default=140000, max_digits=12, verbose_name='قیمت با تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price_without_discount',
            field=models.DecimalField(decimal_places=0, default=140000, max_digits=12, verbose_name='قیمت بدون تخفیف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='post_type',
            field=models.CharField(blank=True, choices=[('irpost', 'شرکت پست'), ('incity', 'درون شهری')], max_length=20, null=True, verbose_name='نوع پست'),
        ),
    ]
