# Generated by Django 3.1.6 on 2021-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20211003_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی قابل پرداخت'),
        ),
    ]
