# Generated by Django 3.1.6 on 2021-10-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_invoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
    ]
