# Generated by Django 3.1.6 on 2021-10-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_remove_invoice_payment_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_unique_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره درخواست پرداخت'),
        ),
    ]
