# Generated by Django 3.1.6 on 2021-10-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_invoice_payment_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='coupon_price',
        ),
    ]
