# Generated by Django 3.1.6 on 2022-01-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0140_auto_20220123_1546'),
        ('invoice', '0027_merge_20211227_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='nakhll_market.product'),
        ),
    ]
