# Generated by Django 3.1.6 on 2022-02-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_auto_20220124_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
    ]
