# Generated by Django 3.2.14 on 2022-07-26 10:02

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_canceled',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ لغو'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_checkout',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه'),
        ),
    ]
