# Generated by Django 3.2.14 on 2022-08-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_auto_20220810_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='coins_amount',
            new_name='coin_amount',
        ),
    ]
